Use makedeb for Debian packaging
PolyMC/PolyMC pull request #104
Opened 2022-01-27 15:53 UTC by dada513

2022-01-27 15:58 UTC, dada513 commented
I also think we should move packaging out of this repo asap

2022-01-27 17:25 UTC, redstrate commented
> I also think we should move packaging out of this repo asap

+1, it makes no sense to include it in this repository, make people clone the whole thing just for a .spec file that downloads another tarball from Github anyway

2022-01-27 17:28 UTC, dada513 commented
Yes and also it’s confusing as to what version is used

2022-01-27 23:16 UTC, hwittenborn requested changes

2022-01-27 23:16 UTC, hwittenborn commented on packages/debian/PKGBUILD
> +  git checkout ${pkgver}
You should be able to replace this with the following under your `source` array:

```sh
source=("git+https://github.com/PolyMC/PolyMC#tag=${pkgver}")
```

2022-01-28 14:35 UTC, binex-dsk commented
I've outlined my reasons for leaving packaging in the repo. Nix absolutely requires to be in the same repo to my knowledge, and it's very convenient to be able to build the Deb straight in the repository. Especially for Jenkins, as it means a full rebuild is not necessary for the deb.

2022-01-28 14:42 UTC, dada513 commented
> 

So I should close this PR?

2022-01-28 14:50 UTC, binex-dsk commented
No, I believe we should leave packaging here. If makedeb works and builds everything properly then this should be good to merge

2022-01-28 18:03 UTC, LennyMcLennington commented
> Nix absolutely requires to be in the same repo to my knowledge

Hard to believe that every single program that nix supports has the packaging scripts in their repo. I don't believe that.

> Especially for Jenkins, as it means a full rebuild is not necessary for the deb.

We can set up Jenkins to have a separate packaging workflow that triggers after a successful build and uses the artifact produced from that to package it.

2022-01-29 08:11 UTC, dada513 commented
since we are moving to MPR and AUR this is not problem anymore  and we could move the packaging to a different repo.
In that repo we should have scripts like update.sh which jenkins will run to upload packages to mpr, aur and copr
No build neccesary except the normal system, portable, windows, appimage
Flatpak can be kept in flathub repo since the updates are made by a bot

> I've outlined my reasons for leaving packaging in the repo. Nix absolutely requires to be in the same repo to my knowledge, and it's very convenient to be able to build the Deb straight in the repository. Especially for Jenkins, as it means a full rebuild is not necessary for the deb.

2022-01-29 14:20 UTC, muscaln commented
> > Nix absolutely requires to be in the same repo to my knowledge
> 
> Hard to believe that every single program that nix supports has the packaging scripts in their repo. Why is it absolutely required specifically for this program?
> 


`nix` is not just a package manager. It also creates development environments from declared derivations. Setting up all required tools is straightforward(`nix develop`). We can move Nix derivation away from this repo but it will just make things more complex.

2022-01-29 14:29 UTC, binex-dsk commented
it's really sussy to build RPM packages in Arch so COPR will have to be done manually for now.

2022-01-29 14:32 UTC, dada513 commented
> it's really sussy to build RPM packages in Arch so COPR will have to be done manually for now.

No we can set up webhook rebuild
You can't upload prebuilt rpm to COPR anyway afaik

2022-01-29 14:34 UTC, dada513 commented
This PR turned to an issue about moving packaging rn lol also since we're using MPR I can close this until we do something like CI upload to MPR (and AUR in that case) or something

2022-01-29 15:48 UTC, binex-dsk commented
CI upload to AUR is finished.

I will however need to make an MPR account

2022-01-29 15:49 UTC, dada513 commented
> CI upload to AUR is finished.
> 
> 
> 
> I will however need to make an MPR account

Nice. When you do that send me your email or something so I can add you

How does the CI aur work? Update script I assume?

2022-01-29 16:27 UTC, binex-dsk commented
It `sed`s the pkgver, updpkgsums, makes the src info, commits, and pushes.

Anyways I registered now, swurl@swurl.xyz. @dada513

2022-01-29 18:08 UTC, dada513 commented
@binex-dsk ook I added u to all the packages

2022-01-30 19:25 UTC, binex-dsk commented
Jenkins now automatically pushes to both the AUR and MPR upon a package update.

The next step is automatically uploading new versions to COPR, @Jan200101 if you could provide details that would be cool and good

2022-01-30 20:53 UTC, Jan200101 commented
> Jenkins now automatically pushes to both the AUR and MPR upon a package update.
> 
> The next step is automatically uploading new versions to COPR, @Jan200101 if you could provide details that would be cool and good

Generally you would run the copr-cli utility (as available on [PyPi](https://pypi.org/project/copr-cli/)) and upload a new .src.rpm or .spec to it.

Generally copr should automatically fetch the needed Sources via the URL specified, though conflicts can come up between Distro releases and repo changes.

To upload stuff you need API access which can be gathered from here https://copr.fedorainfracloud.org/api/

2022-01-30 21:47 UTC, binex-dsk commented
Alright. Does COPR automatically build the RPM? If so then I can have Jenkins update the COPR package. I'd need to have access to push to sentry/polymc though

2022-01-30 21:48 UTC, Jan200101 commented
> Alright. Does COPR automatically build the RPM? If so then I can have Jenkins update the COPR package.

It does upon uploading either a .src.rpm or .spec

> I'd need to have access to push to sentry/polymc though

You would have to create an account either way and at that point it might be better to create a general polymc/polymc copr

2022-01-31 14:55 UTC, binex-dsk commented
Coronavirus disease (COVID-19)

![image](https://user-images.githubusercontent.com/65276418/151816092-4dc7ca71-c80c-42f1-9d59-91a5fcf7178f.png)

2022-01-31 15:07 UTC, dada513 commented
Changed title and content of this PR.
Now it removes all debian packages from the repo, since they are maintained on the MPR.

2022-01-31 15:40 UTC, binex-dsk commented
I already removed the debian stuff but the gitignore I forgot

2022-01-31 15:40 UTC, merged