Custom Yggdrasil account type
PolyMC/PolyMC pull request #1069
Opened 2022-08-19 02:29 UTC by evan-goode

This patch adds a new account type, "Custom Yggdrasil", which internally works much like a Mojang account but lets you specify your own third-party API servers that implement a Yggdrasil-like scheme.

When I refer to "API servers" I specifically mean four hosts:

- the "authentication" server, authserver.mojang.com
- the "account" server, api.mojang.com
- the "session" server, sessionserver.mojang.com
- the "services" server, api.minecraftservices.com

Vanilla Minecraft has built-in support for overriding the API servers at launch without any modifications to the game, which this patch takes advantage of---both the client and server will use the servers specified by the system properties `minecraft.api.*.host`. For example, running the vanilla server, you can specify your own API servers with:

```
java -Xmx1024M -Xms1024M \
	-Dminecraft.api.env=custom \
	-Dminecraft.api.auth.host=https://authserver.example.com \
	-Dminecraft.api.account.host=https://accountserver.example.com \
	-Dminecraft.api.session.host=https://sessionserver.example.com \
	-Dminecraft.api.services.host=https://servicesserver.example.com \
	-jar server.jar nogui
```

Here's an example of an Yggdrasil-compatible API server: https://github.com/rutkai/Mjolnir-Authentication-Server. I'm working on my own as well.

There are lots of reasons players might want to use API servers other than Mojang's. Your community might want to:
- Experience the benefits of offline servers without losing skins, encrypted connections, or account security
- Create additional accounts to allow users to have multiple players logged in to a server simultaneously
	- Have a "camera account" spectate your character for the purpose of content creation
	- Summon [bots](https://mineflayer.prismarine.js.org) to automate tedious tasks like AFKing, crafting, or even building map art. The technical community seems to have settled on Carpet Mod bots for some of these purposes, but if you ran your own authentication server, you could host a fleet of bot-controlled clients without modifying the server at all.
- Play Minecraft in a country or on a network where Mojang's servers are not accessible
- Create your own set of [miniblocks](http://minecraftplayerheadsdatabase.weebly.com/mini-blocks.html)
- Have skins with transparency, or high-resolution skins (would require a modded client as well)
- Have custom capes
- Serve access tokens that last longer, so you don't run into "Invalid session" errors as often. These errors can be annoying with modpacks that take a long time to restart.
- Opt out of Mojang's telemetry and/or chat reporting
- Have a backup authentication system in case Mojang's servers go down

I understand this proposal may be met with some controversy, mainly since it could be construed as enabling piracy. I hope I've given some valid reasons that legitimate, paying customers might want this feature, but I understand this project needs to stay well within the limits of Microsoft's EULA. So I've duplicated the logic from the "offline" account type so that a user can't add a "Custom Yggdrasil" account without first adding a Mojang or MSA account that owns Minecraft. With this DRM check in place, you aren't able to use a custom authentication server to make PolyMC into a "cracked" client.

Last, I'm not advocating that people migrate away from Mojang's infrastructure with this patch. I believe a centralized authentication system is one of Minecraft's greatest strengths---with one account you can play on almost any server. But for people who want to use their own API servers for whatever reason, the method should be as straightforward as possible, ideally baked in to everyone's favorite launcher.

2022-08-19 10:20 UTC, Scrumplex commented
This is an interesting implementation. We are currently a bit divided on this topic internally.
I can clearly see the upsides of this, but I also can see how this can be abused.
We will discuss this further internally.

2022-08-19 13:07 UTC, LennyMcLennington commented
I don't see the problem with this. Could be nice for people who paid for Minecraft, still have a Mojang account and don't intend to migrate, and actually want to play the game with still having the benefits listed instead of just being limited to playing in offline mode with no auth servers.

2022-08-20 11:02 UTC, Scrumplex commented
conflicting with develop

2022-08-20 16:19 UTC, evan-goode commented
Just rebased.

2022-08-21 03:29 UTC, ZekeSmith commented
I'm fine with this change as long as it requires a paid account first.

2022-08-26 16:51 UTC, Trains77 commented
I just tested it and it does require that you have paid account before you can add a custom one

2022-09-14 07:14 UTC, ryanccn commented
This is interesting! When were these command line arguments added? This sort of makes authlib-injector obsolete 😯

I should maybe make https://github.com/ryanccn/freya compatible with this instead of authlib-injector, hmm

2022-10-01 12:13 UTC, Trains77 requested changes
My only suggestion I have would be to check every time the custom account is used if there is a real Minecraft account, so one cannot get the launcher into letting you use the custom account by manually adding it to the accounts.json file

2022-10-01 12:17 UTC, LennyMcLennington commented
> My only suggestion I have would be to check every time the custom account is used if there is a real Minecraft account, so one cannot get the launcher into letting you use the custom account by manually adding it to the accounts.json file

The DRM is enough already.

2022-10-02 13:15 UTC, Scrumplex commented
I have attempted making this DRM stricter in a few PRs already. But as long as @LennyMcLennington objects, I guess we can't do anything.

2022-10-02 16:30 UTC, evan-goode commented
> My only suggestion I have would be to check every time the custom account is used if there is a real Minecraft account, so one cannot get the launcher into letting you use the custom account by manually adding it to the accounts.json file

If this is the threat model, what's to stop someone from adding a fake Minecraft account to the accounts.json file in addition to the custom account? We would have to log in as each MSA or Mojang account and check that at least one of them is valid, each time the launcher starts, right?

Strongly agree with @LennyMcLennington here.

2022-10-05 11:04 UTC, Scrumplex commented
To avoid code duplication, instead of creating a `CustomYggdrasil` account type, maybe you could refactor `Mojang` accounts to support setting a custom URL instead. Then we can just extend our new, let's call it `Yggdrasil` account type with pre-defined auth servers and call that `Mojang`.

2022-10-07 03:48 UTC, evan-goode commented
Yeah, I can try to trim down some of the duplicated code but TBH there isn't a whole lot, since I do reuse `MinecraftProfileStepMojang` and `YggdrasilStep` in `launcher/minecraft/auth/flows/CustomYggdrasil.h`. That auth flow will have to be duplicated anyway since we need a `MigrationEligibilityStep` in the `Mojang` flow, and of course we need the DRM check on custom accounts, so "Mojang" accounts aren't quite just a special case of "Yggdrasil" accounts. I think having a separate `AccountType::CustomYggdrasil` might actually be the most elegant way to do things. An alternative might be a `usesCustomApiServers` flag on `AccountData` which would serve the same purpose.

The biggest duplicated bit is the dialog box, you think I should try to merge those?

Also, for aesthetics, would the name `Yggdrasil` be preferred to `CustomYggdrasil` if we still had a separate `Mojang` and `Yggdrasil` `AccountType`?

2022-11-13 03:39 UTC, binex-dsk commented
this PR should be revisited with DRM removed

2022-11-13 03:41 UTC, LennyMcLennington commented
> this PR should be revisited with DRM removed

With DRM made optional via a compile time flag so that the program can still be distributed in places where such functionality isn't allowed.

2022-11-13 20:09 UTC, binex-dsk commented
Yeah, that would be a good idea, but this will need to be updated with proposed changes as well.

2022-11-18 17:41 UTC, fn2006 commented
Just a heads up for if you do merge this, the JVM arguments that it uses to change the auth server were added in 1.16 which means that it'll function like an offline account if you use it in any version older than 1.16

2022-12-03 18:19 UTC, evan-goode commented
I just opened https://github.com/PrismLauncher/PrismLauncher/pull/543 but I'm happy to continue work here as well.

> @LennyMcLennington: With DRM made optional via a compile time flag so that the program can still be distributed in places where such functionality isn't allowed.

Sounds reasonable, do you think you could add this flag on `develop` and I will rebase and use it?

2023-02-03 01:22 UTC, x0rp01s0n commented
After 1.19 update privatifying the auth system came in as only solution for me,
heres a custom launcher that supports a custom account, https://github.com/MrLetsplay2003/ShittyAuthLauncher ,
technically the game already got taken away from microsoft they took it too far xd

2023-04-15 21:39 UTC, hxr404 commented
> @evan-goode: Sounds reasonable, do you think you could add this flag on `develop` and I will rebase and use it?

Going through the bug tracker I came across this, I think my PR PrismLauncher/PrismLauncher#996 does just that

Feel free to cherry-pick / rebase on / copy&paste my changes
(without credit, I hereby dual license my patch under CC0 in addition to the project's license)

2023-07-06 17:47 UTC, evan-goode commented
Sorry, but I'm closing this to focus on the Prism PR. I don't see a good reason for me to work on PolyMC. Feel free to cherry-pick from my fork.

2023-07-06 17:47 UTC, closed without merging