feat: remove useless actions from instance toolbar
PolyMC/PolyMC pull request #1193
Opened 2022-10-12 13:07 UTC by DioEgizio

removes a few redundant buttons from the instance toolbar

2022-10-12 13:07 UTC, ryanccn commented
why not remove the "instance"s in the buttons

it's an instance sidebar after all, what would it do except change stuff related to the selected instance

2022-10-12 13:12 UTC, Scrumplex commented
Moving our UI changes to 6.0

2022-10-12 13:13 UTC, ryanccn approved these changes
:>

2022-10-12 13:13 UTC, ryanccn requested changes

2022-10-12 13:13 UTC, ryanccn commented on launcher/ui/MainWindow.cpp
> +        actionEditInstance.setTextId(QT_TRANSLATE_NOOP("MainWindow", "Edit."));
Edit.

2022-10-12 13:15 UTC, ryanccn approved these changes
:> 2

2022-10-12 13:19 UTC, LennyMcLennington requested changes
Why is this removing the shortcuts for some of the menu entries? The ...s being removed is fine but I don't think removing the shortcuts makes sense.

2022-10-12 13:21 UTC, DioEgizio commented
I just removed the "instance" part

2022-10-12 13:50 UTC, LennyMcLennington commented
> I just removed the "instance" part

Including the ampersand shortcuts.

2022-10-12 14:26 UTC, flowln commented on launcher/ui/MainWindow.cpp
> +        actionViewSelectedInstFolder.setTextId(QT_TRANSLATE_NOOP("MainWindow", "Folder"));
```suggestion
        actionViewSelectedInstFolder.setTextId(QT_TRANSLATE_NOOP("MainWindow", "&Folder"));
```
also here (not sure if the F is already taken though) :p

2022-10-12 14:31 UTC, Scrumplex commented on launcher/ui/MainWindow.cpp
> -        instanceToolBar->addAction(actionConfig_Folder);
make sure that you delete all `action`s that are unused now.

2022-10-13 17:24 UTC, forkiesassds commented
This seems to fix #1148

2022-10-13 19:28 UTC, Scrumplex commented on launcher/ui/MainWindow.cpp
> +        actionChangeInstGroup.setTextId(QT_TRANSLATE_NOOP("MainWindow", "&Change Group"));
`...` was actually fine, as that implies that a dialog will open.

2022-10-14 02:27 UTC, BeansBeefBroccoli commented
> This seems to fix #1148

Thats what the first message says

2022-10-14 05:30 UTC, DioEgizio commented
> > This seems to fix #1148
> 
> Thats what the first message says
> 
> > Fixes #1148
> > removes a few redundant buttons from the instance toolbar

... Because I edited it after that comment

2022-10-15 10:53 UTC, Scrumplex approved these changes

2022-10-18 12:49 UTC, closed without merging