delete PolyMC
PolyMC/PolyMC pull request #1245
Opened 2022-10-17 20:27 UTC by TaiAurori

smell ya later lenny

https://user-images.githubusercontent.com/31465218/196276297-55a55597-f254-4b0e-9acc-20713f1a10b6.mp4

2022-10-17 20:32 UTC, scottonmars commented
Please

2022-10-17 20:32 UTC, pog5 commented
Merge please, this is a helpful feature.

2022-10-17 20:33 UTC, AwesomePerson2 commented
please delete

2022-10-17 20:33 UTC, greg6775 approved these changes

2022-10-17 20:34 UTC, AwesomePerson2 commented
right now polymc is just a large pile of bullshit

2022-10-17 20:34 UTC, TheFruxz approved these changes
lgtm

2022-10-17 20:35 UTC, micenest approved these changes
this is amazing

2022-10-17 20:35 UTC, humbertovnavarro approved these changes
Looks good to me.

2022-10-17 20:36 UTC, pog5 approved these changes
Merge this asap.

2022-10-17 20:36 UTC, AwesomePerson2 approved these changes
i approve

2022-10-17 20:36 UTC, terminalmaid commented
MERGE IT ***NOW***

2022-10-17 20:36 UTC, TheFruxz approved these changes
Just checked it again, still seems a good idea!

2022-10-17 20:37 UTC, terminalmaid approved these changes
epic

2022-10-17 20:40 UTC, IThundxr approved these changes

2022-10-17 20:41 UTC, TheFruxz commented
seems to fix #1240

2022-10-17 20:41 UTC, flleeppyy reviewed
10/10

2022-10-17 20:41 UTC, Meolsei approved these changes
poggerchampo

2022-10-17 20:41 UTC, flleeppyy approved these changes

2022-10-17 20:41 UTC, DuckyBlender approved these changes
great change :D

2022-10-17 20:42 UTC, cranberry3148 approved these changes

2022-10-17 20:42 UTC, Sterophonick commented
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)

2022-10-17 20:42 UTC, RealY700 commented
Amazing job, I think you should merge this right away!

2022-10-17 20:43 UTC, FlawlessDeveloper approved these changes

2022-10-17 20:43 UTC, PinkGoosik approved these changes

2022-10-17 20:43 UTC, pog5 commented
> ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) [ ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ]( [...]

2022-10-17 20:43 UTC, jakubwesta approved these changes

2022-10-17 20:43 UTC, ooliver1 approved these changes

2022-10-17 20:43 UTC, TheFruxz approved these changes
The third time to check for weird stuff, but still seems valid

2022-10-17 20:43 UTC, FlawlessDeveloper commented
> > ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >       
> >         [
> >           
> >             ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >           
> >         ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >         
> >        [ ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >       
> >         [
> >           
> >             ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >           
> >         ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >         
> >        [ ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >       
> >         [
> >           
> >             ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >           
> >         ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >         
> >        [ ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >       
> >         [
> >           
> >             ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >           
> >         ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >         
> >        [ ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >       
> >         [
> >           
> >             ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >           
> >         ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >         
> >        [ ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >       
> >         [
> >           
> >             ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >           
> >         ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >         
> >        [ ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >       
> >         [
> >           
> >             ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >           
> >         ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >         
> >        [ ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >       
> >         [
> >           
> >             ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >           
> >         ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >         
> >        [ ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif) ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >       
> >         [
> >           
> >             ![poop-dimension](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >           
> >         ](https://user-images.githubusercontent.com/34801996/196279264-ebdf1888-faa8-4716-8b8b-90c6d5dfd1b0.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >             [...]

2022-10-17 20:44 UTC, pog5 approved these changes
Still works fine, tested on TempleOS

2022-10-17 20:44 UTC, TheFruxz commented
![a-lot-of-damage](https://user-images.githubusercontent.com/28064149/196279576-a18f758b-a7ee-4d44-af59-b14b564c789f.gif)

2022-10-17 20:45 UTC, Sterophonick reviewed
looks fine, let's go to the poop dimension

2022-10-17 20:45 UTC, makubas commented
Should be merged

2022-10-17 20:45 UTC, TheFruxz approved these changes
Works on original Macintosh

2022-10-17 20:45 UTC, mothdotmonster commented
Approved for sure

2022-10-17 20:45 UTC, HKGx approved these changes
It's faster and better

2022-10-17 20:46 UTC, RealY700 approved these changes
LGTM

2022-10-17 20:47 UTC, pog5 requested changes
delete the repository too

2022-10-17 20:47 UTC, DarkMetalMouse approved these changes
LGTM!

2022-10-17 20:47 UTC, Xanax-C-137 commented
@TaiAurori please add [a DCO remediation commit](https://github.com/PolyMC/PolyMC/pull/1245/checks?check_run_id=8944316791) and then lgtm

2022-10-17 20:47 UTC, Sterophonick commented
![markiplier-dancing](https://user-images.githubusercontent.com/34801996/196280155-4480e887-5b60-4b3c-afba-1d79618ceb9d.gif)
![markiplier-dancing](https://user-images.githubusercontent.com/34801996/196280155-4480e887-5b60-4b3c-afba-1d79618ceb9d.gif)
![markiplier-dancing](https://user-images.githubusercontent.com/34801996/196280155-4480e887-5b60-4b3c-afba-1d79618ceb9d.gif)
![markiplier-dancing](https://user-images.githubusercontent.com/34801996/196280155-4480e887-5b60-4b3c-afba-1d79618ceb9d.gif)
![markiplier-dancing](https://user-images.githubusercontent.com/34801996/196280155-4480e887-5b60-4b3c-afba-1d79618ceb9d.gif)
![markiplier-dancing](https://user-images.githubusercontent.com/34801996/196280155-4480e887-5b60-4b3c-afba-1d79618ceb9d.gif)

2022-10-17 20:48 UTC, Joshument approved these changes
awesome!

2022-10-17 20:48 UTC, Optinux commented
@LennyMcLennington please merge  
![pmzp0rmm87u51](https://user-images.githubusercontent.com/69096450/196280241-8a83204a-358b-4313-a2b7-4b14cd0e11ac.jpg)

2022-10-17 20:48 UTC, charliekirk1776 approved these changes

2022-10-17 20:49 UTC, DogLoverPink approved these changes

2022-10-17 20:49 UTC, Optinux approved these changes

2022-10-17 20:51 UTC, pog5 commented
[https://gist.github.com/Earthcomputer/dc65391f84a2c19ebac6c33506fd7751](https://gist.github.com/Earthcomputer/dc65391f84a2c19ebac6c33506fd7751)

2022-10-17 20:54 UTC, TaiAurori commented
@Xanax-C-137 sorry fixed

2022-10-17 20:54 UTC, Xanax-C-137 approved these changes

2022-10-17 20:57 UTC, Xanax-C-137 commented
@LennyMcLennington lgtm 🙂

2022-10-17 20:59 UTC, pog5 approved these changes
lgtm

2022-10-17 21:03 UTC, pog5 commented
![image](https://user-images.githubusercontent.com/62222436/196282843-aa65378e-e4ab-40d5-9f97-62fd9fe5cc73.png)

2022-10-17 21:07 UTC, thisismewhenthebeat approved these changes
at a glance this all looks good to me 👍👍👍

2022-10-18 00:00 UTC, closed without merging

2022-10-27 23:53 UTC, ZudoB reviewed
based