Add Slackware package
PolyMC/PolyMC pull request #131
Opened 2022-02-04 16:59 UTC by glowiak

2022-02-04 17:34 UTC, binex-dsk requested changes, later dismissed

2022-02-04 17:34 UTC, binex-dsk commented on README.md
> +If you are too lazy to do all these steps, you can just download [a prebuild x86_64 package](https://codeberg.org/attachments/0547129b-3910-4b46-89fb-50b3221576b1) and install it with /sbin/installpk
nit: command should be in `

2022-02-04 17:40 UTC, dada513 commented
slackware should be as an h3 near other linux distro instructions

2022-02-04 17:44 UTC, dada513 commented on README.md
> +-[Gzipped binaries](https://codeberg.org/attachments/7aa74368-1f55-49be-abd8-0b8258e63e38) - traditional way to distribute, unpack and run.
```suggestion
- [AppBSD Image](https://drive.google.com/file/d/1QLYWGkLSjVb8-lhICivozZQDwYEWBack/view?usp=sharing) - a portable application, requires [AppBSD](https://codeberg.org/glowiak/appbsd/) to be installed.

- [Gzipped binaries](https://codeberg.org/attachments/7aa74368-1f55-49be-abd8-0b8258e63e38) - traditional way to distribute, unpack and run.
``` 

fixed formatting

2022-02-04 17:44 UTC, dada513 commented on README.md
> +## <img src="https://kaworu.ch/images/freebsd-logo.png" height="20" /> FreeBSD
what about using https://www.vectorlogo.zone/logos/freebsd/index.html ? this png scales pretty bad and has a background

```suggestion
## <img src="https://www.vectorlogo.zone/logos/freebsd/freebsd-icon.svg" height="20" /> FreeBSD
```

2022-02-04 17:46 UTC, binex-dsk commented
That's actually a really good point, why google drive?

Additionally, command-line instructions would be big if possible

2022-02-04 19:42 UTC, glowiak commented
Ok, I'll make changes.
Why google drive? Why not? I have private files on yadi.sk, dropbox amount is too small to store all the images, and I want to avoid github everywhere I can

2022-02-04 19:59 UTC, glowiak commented
Okay, now links are static, instructions added (though almost every Slackware or FreeBSD user would know how to do it), and moved Slack to the Linux section

2022-02-04 20:06 UTC, dada513 commented
I would change slackware to an h3 (three hashes), other than that LGTM!

2022-02-04 20:07 UTC, glowiak commented
Oh ok, but anyway, Slackware is the only true Linux distro

2022-02-04 20:08 UTC, dada513 commented
Lol, anyways h3 just to match other distros because os family is h2 distros h3

2022-02-04 20:11 UTC, glowiak commented
window$ belongs to DO$ family, macos is a proprietary copy of FreeBSD

2022-02-05 07:54 UTC, glowiak commented
Changed Slackware to h3

2022-02-05 08:05 UTC, dada513 approved these changes

2022-02-05 11:40 UTC, glowiak commented
So, will you merge the pull request?

2022-02-05 12:34 UTC, dada513 commented
I cant im just a random person. the maintainers are in a different timezone

2022-02-05 13:36 UTC, glowiak commented
I'm compiling PMC to OpenBSD

2022-02-05 15:07 UTC, glowiak commented
added openbsd

2022-02-06 00:59 UTC, binex-dsk commented
Instructions to build packages would be nice. I'd like to mirror these (or atleast the BSD packages) to packages.polymc.org.

2022-02-06 08:31 UTC, glowiak commented
1. Of course, you can copy/mirror these packages.
2. They were built from sources as the BUILD.md file intended, just on OpenBSD changes launcher/tools/MCEditTool.cpp and launcher/UpdateController.cpp to include OBSD. I can make a separate PR to not have to change these files

2022-02-06 08:31 UTC, glowiak commented
Though mirroring also the Slackware package would be nice

2022-02-08 08:38 UTC, glowiak commented
Can anyone merge this?

2022-02-08 12:25 UTC, binex-dsk commented
@LennyMcLennington @txtsd

2022-02-11 10:29 UTC, glowiak commented on README.md
> +If you are too lazy to do all these steps, you can just download [a prebuild x86_64 package](https://codeberg.org/attachments/0547129b-3910-4b46-89fb-50b3221576b1) and install it with /sbin/installpk
Added

2022-02-11 12:00 UTC, txtsd approved these changes
LGTM!

2022-02-11 14:44 UTC, glowiak commented
Could you merge my PRs?

2022-02-11 16:17 UTC, binex-dsk commented
fix conflicts and then @LennyMcLennington

2022-02-14 11:45 UTC, dada513 commented
@glowiak please fix conflicts so that we can merge

2022-02-14 15:55 UTC, Scrumplex approved these changes

2022-02-14 22:30 UTC, LennyMcLennington commented
@glowiak btw what's the best way to contact you about the packages if we need to

2022-02-15 17:04 UTC, glowiak commented
Mail glowiak1111@yandex.com, could you finally merge this pr?

2022-02-15 17:44 UTC, dada513 commented
@glowiak as we said you need to resolve conflicts in README.md before it is merged.

2022-02-16 08:32 UTC, glowiak commented
But it's marked as resolved. What do I need to change?

2022-02-16 08:53 UTC, dada513 commented
> But it's marked as resolved. What do I need to change?

Git conflicts. Develop has changes that conflict with your changes. You need to resolve them via GitHub web using "Resolve Conflicts" button or git cli. Then we can merge it

![image](https://user-images.githubusercontent.com/49000790/154229232-cec4dda4-831a-43e6-a981-ae34acbe9e0e.png)

2022-02-16 20:26 UTC, binex-dsk submitted a review, later dismissed
instructions for BSD manual builds would be cool, that way I can put some on Jenkins

2022-02-17 06:31 UTC, dada513 commented
> instructions for BSD manual builds would be cool, that way I can put some on Jenkins

they are in another PR

2022-02-17 08:59 UTC, timoreo22 approved these changes

2022-02-17 10:08 UTC, glowiak commented
Could you finally merge this pr?

2022-02-17 10:32 UTC, merged

2022-02-17 16:27 UTC, binex-dsk commented
> > instructions for BSD manual builds would be cool, that way I can put some on Jenkins
> 
> they are in another PR

I mean an actual BSD binary package. I don't know if it's just "unpack a generic tarball and run it" or if there's some special file BSD uses. If not then instructions on creating an AppBSD would be cool