Add OpenBSD support
PolyMC/PolyMC pull request #134
Opened 2022-02-06 08:39 UTC by glowiak

title

2022-02-07 03:30 UTC, binex-dsk requested changes

2022-02-07 03:30 UTC, binex-dsk commented on BUILD.md
> +   -DCMAKE_INSTALL_PREFIX="/usr" \ # Replace /usr with /usr/local when building on FreeBSD
include that if you're building outside of a package you should also use /usr/local

2022-02-07 09:12 UTC, glowiak commented
Could you accept my previous pr about Slackware, FreeBSD and OpenBSD packages?

2022-02-08 04:32 UTC, binex-dsk approved these changes

2022-02-09 00:57 UTC, LennyMcLennington commented
@glowiak have you tested this on OpenBSD?

2022-02-09 10:38 UTC, glowiak commented
Yeah, but on 32-bit only, I don't have (yet) any 64-bit OBSD VMs, because now I'm busy at updating software on RedStar OS

2022-02-10 08:49 UTC, dada513 approved these changes

2022-02-11 12:04 UTC, txtsd approved these changes
LGTM!

Although this and #131 could've been a since PR.

2022-02-12 03:30 UTC, merged