Add "Create desktop shortcut" feature.
PolyMC/PolyMC pull request #1516
Opened 2022-11-25 15:19 UTC by xslendix

This PR adds a way of adding a shortcut to directly start an instance as
requested by issues #1088 and #541.

2022-11-26 00:05 UTC, samiscool51 commented
managed to get it to build and run but unfortunately the option to create a shortcut doesn't appear in the instance toolbar:
![image](https://user-images.githubusercontent.com/13957636/204064334-2e3c62b5-3368-4ffc-b267-311e1fb16684.png)
i build it for QT5 on windows 10 LTSC 1809, i'll give QT6 a go to see if it appears there.

2022-11-26 01:05 UTC, samiscool51 commented
update: QT6 version also doesn't have the option sadly.

2022-11-26 11:34 UTC, glowiak commented
Great. For *UNIX you just need to write a .desktop file and place it in ~/.local/share/applications so this would be much easier

2022-11-26 12:54 UTC, xslendix commented
> managed to get it to build and run but unfortunately the option to create a shortcut doesn't appear in the instance toolbar: ![image](https://user-images.githubusercontent.com/13957636/204064334-2e3c62b5-3368-4ffc-b267-311e1fb16684.png) i built it for QT5 on windows 10 LTSC 1809, i'll give QT6 a go to see if it appears there.

This is incredibly weird behaviour, as the option should appear only if not compiled for Macs. Are you sure you compiled correctly? Maybe you forgot to switch branch?

2022-11-26 13:26 UTC, xslendix commented
I have built it on Windows, the option appears but it seems to not do anything.

2022-11-26 13:37 UTC, xslendix commented
I have fixed the issues with the feature on Windows.

2022-11-26 21:39 UTC, samiscool51 commented
>Maybe you forgot to switch branch?
my bad, i forgor to switch branches. tested it again with the correct branch and it launches and works properly.

2022-11-27 17:49 UTC, binex-dsk commented
I'm not big into the idea of including direct windows API calls in MainWindow.cpp, but this looks pretty cool

2022-11-27 18:52 UTC, xslendix commented
> I'm not big into the idea of including direct windows API calls in MainWindow.cpp, but this looks pretty cool

Me neither, but I don't think anyone wants to spend time re-implementing
system libraries.

2022-11-27 19:37 UTC, binex-dsk commented
> > I'm not big into the idea of including direct windows API calls in MainWindow.cpp, but this looks pretty cool
> 
> Me neither, but I don't think anyone wants to spend time re-implementing
> system libraries.

I think the rest of the codebase has some weird `sys_{windows,Unix,etc}.cpp` thing that implements platform-specific functions like getting CPU/RAM information. I'd recommend looking into that; you can define a universal `createInstanceShortcut` function in `sys.h` or whatever it is and then implement it for each OS in the sys files.

2022-11-28 18:41 UTC, xslendix commented
Personally, I would leave it there. If somehow there is a need more system
libraries, then yes, those functions deserve their own special file. I don't
really see the point in making both a C++ source file and header just for one
function.

2022-11-29 02:45 UTC, binex-dsk commented
> Personally, I would leave it there. If somehow there is a need more system
> libraries, then yes, those functions deserve their own special file. I don't
> really see the point in making both a C++ source file and header just for one
> function.
> 

The point I see is for future potential implementations that need system specific libraries.

However you could be a gigachad and force whoever needs that to do it themselves

2022-11-29 18:08 UTC, binex-dsk requested changes

2022-11-29 18:08 UTC, binex-dsk commented on launcher/ui/MainWindow.cpp
> +        const_cast<wchar_t *>(executable_path.toStdWString().c_str()),
Any reason for the const_casts here? Why not make the LPCWSTR arguments const refs?

2022-11-30 02:33 UTC, binex-dsk approved these changes

2022-11-30 02:34 UTC, binex-dsk commented
I'd leave this as a draft until it gets implemented and tested on MacOS

2022-11-30 06:32 UTC, xslendix commented
> I'd leave this as a draft until it gets implemented and tested on MacOS

I will not be implementing this for Mac, as I have zero familiarity with it's internals. If someone wants to add support for it, a new PR can always be made.

2022-11-30 12:05 UTC, binex-dsk commented
> > I'd leave this as a draft until it gets implemented and tested on MacOS
> 
> I will not be implementing this for Mac, as I have zero familiarity with it's internals. If someone wants to add support for it, a new PR can always be made.

zased?

2023-01-04 20:20 UTC, LennyMcLennington commented
Does it want Qt::endl? instead of just endl?

2023-06-02 15:18 UTC, LennyMcLennington commented
Does this work with flatpak and appimage?

2024-11-13 20:14 UTC, merged