UI/UX tweaks and quality of life - remastered
PolyMC/PolyMC pull request #1517
Opened 2022-11-25 16:48 UTC by xslendix

Since Zeke is now gone, I think it's safe to say, work on PR #1103 has seized.
As such, I have decided to take this into my own hands. Drop your ideas in the
comments on what you think I should change about the UI/UX in order to make it
more friendly to beginners.

2022-11-25 17:02 UTC, slendidev commented
> Screenshots?

[Here you go](https://imgur.com/a/iqewcMU)

2024-07-28 21:25 UTC, xslendix commented
@LennyMcLennington What do you want changed?

2024-07-28 21:27 UTC, Sneedplex approved these changes
LGTM.

2024-11-13 20:09 UTC, LennyMcLennington requested changes
loader needs to be an enum

2024-11-13 22:51 UTC, xslendix commented
@LennyMcLennington if I make it an enum, I would need it to have a function that returns a string constant based on the value, do you have a preferred way of implementing that or just hardcode everything in that said function?

2024-11-14 03:53 UTC, Sneedplex commented
> @LennyMcLennington if I make it an enum, I would need it to have a function that returns a string constant based on the value, do you have a preferred way of implementing that or just hardcode everything in that said function?

just use a QMap<LoaderType, QString>

2024-11-14 11:06 UTC, xslendix commented
@Sneedplex That's a very bad idea for a couple of reasons:

1. The data is mutable
2. It adds CPU strain because of hashing
3. It uses more memory than needed

I was going to make an enum of values, where I can then have a function where you pass in the value and returns a `char const *`.

2024-11-15 03:27 UTC, Sneedplex commented
1. const exists for a reason retard
2. if your CPU can't handle a single enum hash then it might be over for you, if you're that autistic just use a QHash
3. oh no a whole 100 bytes

2024-11-15 23:55 UTC, DoubleHypercube commented
> It adds CPU strain because of hashing

How's Prescott treating you?

2024-11-16 13:21 UTC, xslendix commented
@Sneedplex @AutumnalModding This is how software turns to shit, people like you. No wonder modern software takes years to open for example, you just don't give a shit at all. It would be much faster to just return a fucking address and doing a simple comparison on the enum value. Or make a static constant array, and use the enum value as an index.

2024-11-16 14:24 UTC, crueter commented
It's 100 bytes of memory and a picosecond of computation time. If you're that concerned about micro-optimizations then you wouldn't be using Qt, leave your autism at the door or create your own shitty CLI launcher in x86 assembly.

2024-11-16 14:53 UTC, LennyMcLennington commented
@crueter @xslendix @Sneedplex Instead of whining or speculating I have prepared some example code for you:

https://godbolt.org/z/oMdreervn
https://godbolt.org/z/qedP1h74v
https://godbolt.org/z/z1bTW5v98

Honestly, I don't care which approach you take or if you take a completely different approach, I just want it to not have arbitrary strings floating around in random parts of the code.

2024-11-16 14:55 UTC, LennyMcLennington commented
Also please try not to use Qt containers when a standard one suffices.

2024-11-16 15:07 UTC, LennyMcLennington commented
Also I just had the thought that since we're on C++17 now we could also use std::optional instead of throwing ig.

2024-11-16 15:10 UTC, Sneedplex approved these changes

2024-11-16 15:14 UTC, Sneedplex commented
these old PRs are so autistic because none of them build properly thanks to the QList<>::iterator change that I cba to fix every time

2024-11-16 15:15 UTC, LennyMcLennington commented
> these old PRs are so autistic because none of them build properly thanks to the QList<>::iterator change that I cba to fix every time

Can't you just rebase them onto devleop?

2024-11-16 15:19 UTC, LennyMcLennington commented
> these old PRs are so irritating because none of them build properly thanks to the QList<>::iterator change that I cba to fix every time

@Sneedplex can't you just rebase it?

2024-11-16 15:20 UTC, Sneedplex commented
> > these old PRs are so irritating because none of them build properly thanks to the QList<>::iterator change that I cba to fix every time
> 
> @Sneedplex can't you just rebase it?

Yeah but I don't want to push when I've rebased the entirety of develop onto the branch and it's annoying to go back.

2024-11-16 15:21 UTC, Sneedplex commented
@xslendix i need to push a quick fix turn on maintainer edits again.

2024-11-16 15:22 UTC, LennyMcLennington commented
> Yeah but I don't want to push when I've rebased the entirety of develop onto the branch and it's annoying to go back.

@Sneedplex if you want to rebase the PR onto develop and force push that's fine.

2024-11-16 20:37 UTC, LennyMcLennington reviewed
I would prefer if you only formatted code that you modified, so that I don't have to look through an entire page of whitespace diffs just to figure out what you changed.

2024-11-16 20:39 UTC, LennyMcLennington commented on launcher/minecraft/mod/ModDetails.h
> +[[maybe_unused]] static QString const ModLoader_string(ModLoader const mod_loader)
maybe unused? static? should this not just be inline?

2024-11-16 22:05 UTC, AutumnalModding commented
> No wonder modern software takes years to open for example

@xslendix Sorry, did I say Prescott? I guess I meant to say "How's your 286 treating you?".

2024-11-16 22:21 UTC, LennyMcLennington commented
@AutumnalModding please stop posting unconstructive comments on a PR that doesn't involve you. I let it slide the first time.

2024-11-16 22:29 UTC, AutumnalModding commented
OK, my bad

2026-09-08 03:16 UTC, crueter commented
This PR is ancient but contains some decent changes, should probably be split up into a few distinct PRs.

2026-09-10 05:54 UTC, slendidev commented
yea idc about this anymore

2026-09-10 05:54 UTC, closed without merging