Add option to always start PolyMC fullscreen.
PolyMC/PolyMC pull request #1527
Opened 2022-12-30 13:41 UTC by xslendix

Closes #1176.

2022-12-30 16:54 UTC, binex-dsk requested changes

2022-12-30 16:54 UTC, binex-dsk commented on launcher/ui/pages/global/LauncherPage.ui
> +             <string>Start fullscreen</string>
Probably capitalize the F

2022-12-30 16:54 UTC, binex-dsk commented on launcher/ui/pages/global/LauncherPage.ui
> +      <number>1</number>
Common Qt Designer L

2022-12-30 18:05 UTC, xslendix commented on launcher/ui/pages/global/LauncherPage.ui
> +      <number>1</number>
I HATE QT DESIGNER I HATE QT DESIGNER I HATE QT DESIGNER I HATE QT DESIGNER I HATE QT DESIGNER I HATE QT DESIGNER I HATE QT DESIGNER I HATE QT DESIGNER I HATE QT DESIGNER I HATE QT DESIGNER

2023-01-13 00:12 UTC, LennyMcLennington commented
What's the benefit of starting in fullscreen mode on top of everything? PolyMC already remembers the window geometry you closed with.

2023-02-14 22:14 UTC, LennyMcLennington commented
@xslendix I looked at the issue that this apparently closed, and it's asking for 'start maximised' not 'start fullscreen'.

2023-06-04 17:47 UTC, xslendix commented
This PR is not relevant to the issues it's trying to fix and I do not think it's even remotely useful. Closing, might make a PR that actually addresses the issue raised.

2023-06-04 17:47 UTC, closed without merging