Add Pallas's cat (Otocolobus manul) :3
PolyMC/PolyMC pull request #1556
Opened 2023-02-20 17:24 UTC by Sightem

I was looking at the selection combo box and there was no manul option?! how could this be?? this pull request should fix this issue

2023-02-20 17:30 UTC, Sightem commented
previews:

![manulxmas](https://user-images.githubusercontent.com/67830794/220169977-66f8cbe8-fbff-458a-aa4d-bfdda64e8f79.png)![manulbg](https://user-images.githubusercontent.com/67830794/220170052-56d96701-b2bf-4429-8380-562079b0a781.png)![manulversary](https://user-images.githubusercontent.com/67830794/220170157-802503d0-6109-4f56-a406-e04c9f0eb45f.png)

2023-02-20 17:45 UTC, namedata commented
yes please do this

2023-02-20 19:20 UTC, xslendix commented
cute gato

2023-02-20 20:10 UTC, glowiak commented
Well seems like everyone is adding their own cats now. Why can't everyone just don't use the cat as I do?

2023-02-20 20:44 UTC, LennyMcLennington requested changes

2023-02-20 20:44 UTC, LennyMcLennington commented on launcher/ui/MainWindow.cpp
>          else if(catStyleOpt == "Jinx")
```suggestion
        
        if(catStyleOpt == "Manul")
            cat = "manul";
        else if(catStyleOpt == "Floppa")
            cat = "floppa";
        else if(catStyleOpt == "Jinx")
```

2023-02-21 01:27 UTC, Sightem commented
fixed the commit sign offs

2023-05-17 13:03 UTC, Gentleman2292 commented
MANUL

2024-11-13 03:21 UTC, Sneedplex approved these changes
cat

2024-11-13 19:51 UTC, merged