Clarified the README file
PolyMC/PolyMC pull request #1558
Opened 2023-02-22 19:49 UTC by NikNikovsky

2023-02-22 22:01 UTC, LennyMcLennington requested changes
Most of these changes just make it grammatically or factually incorrect.

2023-02-22 22:01 UTC, LennyMcLennington commented on README.md
> +There are per-commit development builds available [here](https://github.com/PolyMC/PolyMC/actions). These have to debug information in the binaries, so their file sizes are relatively larger.
This is just incorrect

2023-02-22 22:01 UTC, LennyMcLennington commented on README.md
> +Feel free to create an issue if you need help. However, you might find it easier to ask on the Discord server.
This is just incorrect

2023-02-22 22:01 UTC, LennyMcLennington commented on README.md
> +PolyMC is a custom launcher for Minecraft that focuses on predictability, long-term stability, and simplicity.
This is fine

2023-02-22 22:27 UTC, NikNikovsky commented on README.md
> +There are per-commit development builds available [here](https://github.com/PolyMC/PolyMC/actions). These have to debug information in the binaries, so their file sizes are relatively larger.
Will fix

2023-02-22 22:27 UTC, NikNikovsky commented on README.md
> +Feel free to create an issue if you need help. However, you might find it easier to ask on the Discord server.
Will fix

2023-02-22 22:30 UTC, NikNikovsky commented on README.md
> +There are per-commit development builds available [here](https://github.com/PolyMC/PolyMC/actions). These have to debug information in the binaries, so their file sizes are relatively larger.
Fixed

2023-02-22 22:30 UTC, NikNikovsky commented on README.md
> +Feel free to create an issue if you need help. However, you might find it easier to ask on the Discord server.
Fixed

2023-02-22 22:30 UTC, NikNikovsky commented on README.md
> +PolyMC is a custom launcher for Minecraft that focuses on predictability, long-term stability, and simplicity.
If it's fine, why bother fixing

2023-02-23 10:19 UTC, closed without merging

2023-02-23 11:18 UTC, NikNikovsky commented
I didn't have time to do it.
(I am in the GMT+1 timezone)