CI: Release builds and workflow
PolyMC/PolyMC pull request #158
Opened 2022-02-12 14:56 UTC by txtsd

Commits and PRs now trigger builds of, both, type Debug and Release, for Linux, Windows, and macOS, for a total of 6 artifacts.

If a tag is pushed, a GH Release is created in Draft mode, and the artifacts are packaged properly and then attached to the GH Release. We can then assimilate a changelog and make it public. The name of the tag is used as the version in the filenames.

Due to GH limitations, one tag can only be operated on once. If a tag is deleted and recreated, GH will not operate on it.

2022-02-12 17:29 UTC, Scrumplex requested changes
If we start the release on a branch other than `stable` we will get an ugly suffix to the version string with the current branch, see #160.

2022-02-12 17:29 UTC, Scrumplex commented on .github/workflows/trigger_builds.yml
> +    if: startsWith(github.ref, 'refs/tags/')
Make sure this runs ONLY on stable.

2022-02-12 17:29 UTC, Scrumplex commented on .github/workflows/trigger_builds.yml
> +    needs: create_release
ditto!

2022-02-12 17:30 UTC, Scrumplex commented on .github/workflows/trigger_builds.yml
> +    needs: create_release
nvm! lol

2022-02-12 18:14 UTC, Scrumplex commented
We need to ensure that `HEAD` when building a release is pointing at the `stable` branch. If we don't, then `Launcher_GIT_REFSPEC` in `CMakeLists.txt` will be empty (by default on GHA).

2022-02-13 03:44 UTC, txtsd commented
Okay I'll see what I can do

2022-02-13 06:06 UTC, txtsd commented
> We need to ensure that `HEAD` when building a release is pointing at the `stable` branch. If we don't, then `Launcher_GIT_REFSPEC` in `CMakeLists.txt` will be empty (by default on GHA).

Aren't we going to assign each new version to its own branch? If we only build stable, how will building the versioned branches work?

2022-02-13 09:39 UTC, Scrumplex commented
> > We need to ensure that `HEAD` when building a release is pointing at the `stable` branch. If we don't, then `Launcher_GIT_REFSPEC` in `CMakeLists.txt` will be empty (by default on GHA).
> 
> Aren't we going to assign each new version to its own branch? If we only build stable, how will building the versioned branches work?

I think we haven't defined a release workflow at all, but I would assume it goes like this:
- We decide that we want to release a release
- Bump version in CMakeLists.txt
- Tag this commit with the version number
- Create a PR to merge this into stable
- Merge
- GHA creates a release

2022-02-13 09:44 UTC, txtsd commented
Okay I'll add a branch condition and see if it works with that flow.

2022-02-15 10:01 UTC, txtsd commented
> I think we haven't defined a release workflow at all, but I would assume it goes like this:
> 
>     * We decide that we want to release a release
> 
>     * Bump version in CMakeLists.txt
> 
>     * Tag this commit with the version number
> 
>     * Create a PR to merge this into stable
> 
>     * Merge
> 
>     * GHA creates a release

Is it possible to tag the commit on the stable branch instead?

2022-02-15 14:48 UTC, Scrumplex commented
Yeah, is probably even the only way, as I think PRs don't merge tags as well.

2022-02-16 06:16 UTC, txtsd commented on .github/workflows/trigger_builds.yml
> +    if: startsWith(github.ref, 'refs/tags/')
Done!

2022-02-16 06:18 UTC, txtsd commented
This will need a change if merged after #163

2022-02-16 16:57 UTC, Scrumplex approved these changes
LGTM

2022-02-16 17:20 UTC, dada513 approved these changes

2022-02-17 07:01 UTC, dada513 commented
Remove MacOS release builds, they weigh 1mb more and make the build longer.

2022-02-17 08:43 UTC, txtsd commented
> Remove MacOS release builds, they weigh 1mb less than debug and make the build longer.

The macOS builds are the fastest builds, and the matrix runs in parallel so it shouldn't matter.

2022-02-18 09:56 UTC, dada513 commented
Do we need debug builds for releases? It would just make it harder for users to pick the correct file. I think we only need release builds for releases

2022-02-18 13:13 UTC, d-513 commented
also add lin-system build for bin packages

2022-02-18 13:43 UTC, txtsd commented
> Do we need debug builds for releases? It would just make it harder for users to pick the correct file. I think we only need release builds for releases

These will only be in the artifacts. The GH release itself will only have the 3 release builds.

EDIT: [Release examples](https://github.com/txtsd/PolyMC/releases)

2022-02-18 13:44 UTC, txtsd commented
> also add lin-system build for bin packages

lin-system was not working for everyone. Me included. Qt errors.

2022-02-18 13:45 UTC, timoreo22 approved these changes

2022-02-18 16:07 UTC, txtsd commented
@dada513 wants release filenames with no version in them. This is okay from an automation perspective.

What are everyone else's opinions?

2022-02-19 18:15 UTC, dada513 commented
Can we get this merged? I would like to start working on MPR and AUR upload and flatpak-

2022-02-21 16:28 UTC, txtsd commented
Now also builds and packages a generic Linux build for use with package managers.
Need @dada513 to confirm whether they're working as intended.

Also, building for pushes and PRs etc triggers from a different workflow, and pushing a tag to make a release triggers from a different workflow.

2022-02-21 18:31 UTC, timoreo22 commented
While testing the generic linux i still get
`./polymc: symbol lookup error: ./polymc: undefined symbol: _ZdlPvm, version Qt_5
`

2022-02-21 18:48 UTC, Scrumplex commented
I think we need to bundle Qt. We just can't expect ABI compatibility for Qt as it's a rather fast moving target.

2022-02-22 02:40 UTC, txtsd commented
> I think we need to bundle Qt. We just can't expect ABI compatibility for Qt as it's a rather fast moving target.

How would we go about bundling Qt in a regular tarball? Installing it would overwrite system libraries.

2022-02-22 02:41 UTC, binex-dsk commented
lin-nodeps

2022-02-22 02:50 UTC, txtsd commented
> lin-nodeps

We didn't even use `lin-nodeps` on Jenkins.

2022-02-22 03:19 UTC, binex-dsk commented
yes but Jenkins was on Arch so it worked for most people, this is on Ubuntu so it's really sussy with lin-system

2022-02-22 04:37 UTC, txtsd commented
Okay, apparently `_ZdlPvm` is the sized operator delete, and it should not be in an ELF. This is caused by the Qt that we pull using `aqt`. I'm going to try using system Qt instead.

2022-02-22 15:40 UTC, txtsd commented
Okay generic Linux builds now use system Qt instead of Qt downloaded with `aqt`. It doesn't throw the `symbol lookup error` anymore.

2022-02-22 15:41 UTC, txtsd commented
This is ready for a merge now. Once this is in, I'll rebase #163.

2022-02-23 09:36 UTC, merged