Add MSA-Client-ID override in UI
PolyMC/PolyMC pull request #161
Opened 2022-02-12 19:40 UTC by Scrumplex

Closes #11.

The user can now override the MSA client ID provided at build time with their own. If neither build environment nor the user provide a client ID, the MSA login option will be disabled as usual.

Additionally, this PR renames the "Log Upload" settings page to "APIs".

![Settings page](https://scrumplex.rocks/img/1644694718.png)

![Settings page but based](https://scrumplex.rocks/img/1644694816.png)

2022-02-12 19:43 UTC, LennyMcLennington commented
MSA stands for Microsoft Account

2022-02-12 19:46 UTC, Scrumplex commented
According to [Migration FAQ](https://help.minecraft.net/hc/en-us/articles/360050865492-Minecraft-Java-Edition-Account-MIgration-FAQ) it actually stands for Microsoft Secured Account.

![Screenshot proving that I am right](https://scrumplex.rocks/img/1644695099.png)

2022-02-12 19:47 UTC, LennyMcLennington commented
According to Microsoft's documentation it stands for Microsoft Account, I wonder if the "Secured" part was something Mojang just made up as part of their "Forced Migration = Security Update" propaganda campaign?

2022-02-12 19:53 UTC, Scrumplex commented
I dunno. Let's make a vote on how we should call it.

- React with :+1: : if you think it should be `Microsoft Secured Account` (like it is noww)
- React with :rocket: if you think it should be `Microsoft Account`
- React with :eyes: if you think it should be `Microsoft Authentication`

2022-02-12 19:58 UTC, timoreo22 approved these changes
Already approving this for now, can merge after the string is changed

2022-02-12 20:09 UTC, Scrumplex commented
~~Actually it stands for `MSA`~~ Microsoft Authentication wins.

2022-02-12 20:11 UTC, Scrumplex commented
Now it looks like this:

![Settings page but with Microsoft Authentication](https://scrumplex.rocks/img/1644696621.png)

2022-02-12 20:19 UTC, LennyMcLennington commented on launcher/Application.cpp
> +    auto clientIDOverride = m_settings->get("MSAClientIDOverride").toString();
this is nitpicky but why are you using auto here but using QString in the other place where you get the setting
```suggestion
    QString clientIDOverride = m_settings->get("MSAClientIDOverride").toString();
```
other than this lgtm

2022-02-13 02:07 UTC, ghost requested changes
>using organized commit names

Commit everything as "bruh spaghetti {1,2,..} and I will approve this

2022-02-13 03:13 UTC, LennyMcLennington approved these changes

2022-02-13 08:15 UTC, d-513 approved these changes

2022-02-13 14:06 UTC, merged