Make Java auto-detect find sdkman Java installations
PolyMC/PolyMC pull request #1631
Opened 2024-01-02 10:42 UTC by HeyaGlitz

Fixes https://github.com/PolyMC/PolyMC/issues/1630

2024-01-04 05:36 UTC, binex-dsk requested changes

2024-01-04 05:36 UTC, binex-dsk commented on launcher/java/JavaUtils.cpp
> +    scanJavaDir(FS::PathCombine(std::getenv("HOME"), ".sdkman/candidates/java"));
You can use QDir::homeDir() instead.

2024-01-05 21:29 UTC, binex-dsk commented
Any reason to use FS::PathCombine rather than std::filesystem::path or string concatenation?

2024-01-05 22:57 UTC, HeyaGlitz commented
FS::PathCombine is already previously used in this source file therefore I think that it's best to be consistent at least. Those two methods would work perfectly fine though.

2024-01-05 23:06 UTC, binex-dsk commented
Undocumented code using random useless methods🔥🔥🔥

2024-01-05 23:07 UTC, binex-dsk approved these changes

2024-01-06 13:51 UTC, merged