Add issue template for RFCs
PolyMC/PolyMC pull request #169
Opened 2022-02-15 14:11 UTC by Scrumplex

To encourage more RFCs let's add an issue template.
This form uses the [template used by the Arch Linux project](https://gitlab.archlinux.org/archlinux/rfcs/-/blob/0ba3b61e987e197f8d1901709409b8564958f78a/rfcs/0000-template.rst).

---

![How the form looks](https://user-images.githubusercontent.com/11587657/154078452-f18d4bc2-b5ed-471b-953c-4338cfbedd53.png)

2022-02-15 23:29 UTC, tonyaellie commented
change Arch Linux to PolyMC on line 21?

2022-02-16 03:53 UTC, binex-dsk requested changes

2022-02-16 03:53 UTC, binex-dsk commented on .github/ISSUE_TEMPLATE/rfc.yml
> +    placeholder: Does a substatial amount of users care about the cat?
do*

2022-02-16 03:53 UTC, binex-dsk commented on .github/ISSUE_TEMPLATE/rfc.yml
> +    placeholder: Maybe the cat could be replaced with an axolotl?
replace axolotl with sneed

2022-02-16 07:28 UTC, dada513 commented on .github/ISSUE_TEMPLATE/rfc.yml
> +    placeholder: Does a substatial amount of users care about the cat?
no

2022-02-16 07:28 UTC, dada513 commented on .github/ISSUE_TEMPLATE/rfc.yml
> +    placeholder: Maybe the cat could be replaced with an axolotl?
no

2022-02-16 07:30 UTC, dada513 requested changes

2022-02-16 07:30 UTC, dada513 commented on .github/ISSUE_TEMPLATE/rfc.yml
> +      Introduce the topic. If this is a not-well-known section of Arch Linux, a detailed explanation of the background is recommended.
```suggestion
      Introduce the topic. If this is a not-well-known section of PolyMC, a detailed explanation of the background is recommended.
```

2022-02-16 14:13 UTC, timoreo22 approved these changes
Cool !

2022-02-16 14:31 UTC, dada513 approved these changes

2022-02-16 20:21 UTC, binex-dsk commented
replace axolotl with sneed

2022-02-16 20:21 UTC, binex-dsk approved these changes

2022-02-22 14:10 UTC, merged