Detect MSA Client ID change
PolyMC/PolyMC pull request #180
Opened 2022-02-18 11:35 UTC by Scrumplex

This will detect which client ID was used to log in and disable the account if it doesn't match the one configured right now.

Screenshot when trying to start an instance (Account disabled):
![Screenshot of dialog](https://scrumplex.rocks/img/1645184089.png)

2022-02-18 11:36 UTC, Scrumplex commented
Complementary PR to #172 and #161

2022-02-18 13:14 UTC, d-513 approved these changes

2022-02-18 13:48 UTC, txtsd requested changes

2022-02-18 13:48 UTC, txtsd commented on launcher/LaunchController.cpp
> +                auto errorString = tr("The launcher's client identification changed. Please remove this account and add it again.");
Can you make this `has changed`? Without `has` it sounds like it might be of the user's doing.

2022-02-18 20:00 UTC, txtsd approved these changes

2022-02-19 13:58 UTC, dada513 commented
sorry txtsd I missclicked

2022-02-19 14:41 UTC, txtsd approved these changes
Dangit I'll approve it again!

2022-02-19 14:47 UTC, timoreo22 approved these changes

2022-02-20 12:58 UTC, LennyMcLennington approved these changes

2022-02-22 07:23 UTC, merged