Switch to polymc.org wiki
PolyMC/PolyMC pull request #232
Opened 2022-03-05 20:49 UTC by Scrumplex

Closes #217

2022-03-06 06:16 UTC, timoreo22 approved these changes

2022-03-06 07:46 UTC, dada513 requested changes
can you make this a build option? most URLs arent hardcoded, and its better to have it modular

2022-03-06 10:33 UTC, dada513 approved these changes

2022-03-07 14:22 UTC, ZekeSmith approved these changes
Looks good

2022-03-07 14:22 UTC, merged