Update BUILD.md to link to the wiki.
PolyMC/PolyMC pull request #241
Opened 2022-03-08 09:13 UTC by ZekeSmith

2022-03-08 19:38 UTC, glowiak commented
But why?

2022-03-09 19:05 UTC, dada513 approved these changes

2022-03-09 19:33 UTC, Scrumplex approved these changes

2022-03-09 19:40 UTC, dada513 commented
> But why?

All documentation is now maintained on wiki, for ease of use and contributing.

2022-03-10 18:29 UTC, glowiak approved these changes
ok

2022-03-10 19:13 UTC, txtsd requested changes

2022-03-10 19:13 UTC, txtsd commented on BUILD.md
> +If you would like to contribute or fix an issue with the Build instructions your can do so [here](https://github.com/PolyMC/polymc.github.io/blob/master/src/wiki/development/build-instructions.md)
s/your/you/

2022-03-11 09:12 UTC, txtsd approved these changes

2022-03-11 09:42 UTC, merged