Switch to msys2 for Windows builds
PolyMC/PolyMC pull request #294
Opened 2022-03-18 07:57 UTC by oynqr

This switches Windows builds to use dependencies from msys2/mingw64. Benefits are updated/patched QT and OpenSSL, *probably* working x86_64 builds and *hopefully* no more weird issues. The only downside so far is the increased binary size, plus build times for i686 are abysmal.

AdoptOpenJDK is also replace by Eclipse Temurin since the former is no longer supported.

Closes #222

2022-03-18 08:11 UTC, DioEgizio commented
> probably working x86_64 builds

They work for me

2022-03-18 09:43 UTC, txtsd commented
Going to test these on my Win10 VM.

2022-03-18 10:42 UTC, Scrumplex commented
Maybe this fixes #276 as well

2022-03-18 17:26 UTC, Scrumplex requested changes

2022-03-18 17:26 UTC, Scrumplex commented on .github/workflows/build.yml
> +          name: PolyMC-${{ matrix.name }}-${{ inputs.build_type }}
macOS and Linux don't have `.name`. Look at the filenames: https://github.com/PolyMC/PolyMC/actions/runs/2002938513

2022-03-18 17:26 UTC, Scrumplex commented on .github/workflows/build.yml
> -          echo "VERSION=$ver_short" >> $GITHUB_ENV
Why is `$VERSION` gone?

2022-03-18 21:20 UTC, oynqr commented on .github/workflows/build.yml
> -          echo "VERSION=$ver_short" >> $GITHUB_ENV
oops

2022-03-19 00:43 UTC, ZekeSmith approved these changes

2022-03-20 06:42 UTC, txtsd commented
x64 builds work for me!

Now that x64 is possible, do we even need to build a 32bit binary? We don't do it for any other platform, so I feel like we shouldn't have to for Windows either. We historically only offered a 32bit binary because we couldn't get 64bit to work.

2022-03-20 06:44 UTC, DioEgizio commented
I mean, it's another build so why not
But it's the slowest, so idk
Also who even uses Minecraft on a 32bit pc

2022-03-20 08:28 UTC, Scrumplex approved these changes

2022-03-20 12:44 UTC, Scrumplex commented
Let's keep 32-bit builds for now. We can probably remove them for 1.2.0.

2022-03-20 13:50 UTC, Scrumplex commented
We should definitely update our build instructions to use MSYS2 as well.

2022-03-20 13:51 UTC, LennyMcLennington commented
> Let's keep 32-bit builds for now. We can probably remove them for 1.2.0.

Why? What is the problem with 32 bit builds?

2022-03-20 13:58 UTC, ZekeSmith approved these changes

2022-03-20 13:59 UTC, DioEgizio commented
> > Let's keep 32-bit builds for now. We can probably remove them for 1.2.0.
> 
> Why? What is the problem with 32 bit builds?

they're fine but they take forever to build

2022-03-20 14:00 UTC, txtsd commented
> > Let's keep 32-bit builds for now. We can probably remove them for 1.2.0.
> 
> Why? What is the problem with 32 bit builds?


> Now that x64 is possible, do we even need to build 
a 32bit binary? We don't do it for any other platform, so I feel like we shouldn't have to for Windows either. We historically only offered a 32bit binary because we couldn't get 64bit to work.

2022-03-20 14:00 UTC, txtsd approved these changes
LGTM!

2022-03-20 14:01 UTC, merged