bring back not portable windows builds
PolyMC/PolyMC pull request #330
Opened 2022-03-21 18:56 UTC by DioEgizio

Closes #327

2022-03-21 19:54 UTC, Scrumplex requested changes

2022-03-21 19:54 UTC, Scrumplex commented on .github/workflows/build.yml
> +      - name: Build on Windows
nit: trailing space

2022-03-21 19:54 UTC, Scrumplex commented on .github/workflows/build.yml
> +
nit: new linebreak

2022-03-21 19:54 UTC, Scrumplex commented on .github/workflows/build.yml
> +          cmake -S . -B ${{ env.BUILD_DIR }} -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_DIR }} -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} -G Ninja -DLauncher_PORTABLE=OFF
nit: put `-G Ninja` at the end

2022-03-22 13:41 UTC, Scrumplex approved these changes

2022-03-22 14:52 UTC, cozyGalvinism approved these changes

2022-03-22 14:54 UTC, d-513 approved these changes

2022-03-22 15:42 UTC, merged