Add quit launcher after game stops option (Steam Deck)
PolyMC/PolyMC pull request #341
Opened 2022-03-23 18:09 UTC by dada513

Allows for launcher to quit directly after the game stops. This is useful for the Deck where you want to just get to the steam menu
 Best combined with "Hide launcher after game window starts"

2022-03-24 04:13 UTC, txtsd approved these changes

2022-03-24 08:35 UTC, ZekeSmith approved these changes

2022-03-24 10:27 UTC, Scrumplex requested changes

2022-03-24 10:27 UTC, Scrumplex commented on launcher/minecraft/launch/LauncherPartLaunch.cpp
> +            }
I don't like that this is here. LauncherPartLaunch is one of many steps of a game launch. If we close here, all later steps will probably not run anymore (or there will be a race condition). This should be implemented as an additional step (see https://github.com/PolyMC/PolyMC/blob/92f3154e8f7c1421541a00ae7cf57f188cfe46a5/launcher/minecraft/MinecraftInstance.cpp#L906-L933)

2022-03-24 10:31 UTC, d-513 commented on launcher/minecraft/launch/LauncherPartLaunch.cpp
> +            }
I agree, will try to fix when I'm home

2022-03-27 11:05 UTC, Scrumplex approved these changes
looks good

2022-03-27 11:05 UTC, Scrumplex commented on launcher/launch/steps/QuitAfterGameStop.cpp
> +}
nit: no newline at the end of the file

2022-03-27 11:05 UTC, Scrumplex commented on launcher/launch/steps/QuitAfterGameStop.cpp
> +#include "QuitAfterGameStop.h"
nit: license header maybe?

2022-03-27 11:05 UTC, Scrumplex commented on launcher/launch/steps/QuitAfterGameStop.h
> +#pragma once
nit: license header maybe?

2022-03-27 11:07 UTC, Scrumplex commented
You can use this as the license header for new files:
```c
// SPDX-License-Identifier: GPL-3.0-only
/*
 *  PolyMC - Minecraft Launcher
 *  Copyright (C) 2022 dada513 <dada513@protonmail.com>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, version 3.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

2022-03-27 12:52 UTC, dada513 commented on launcher/launch/steps/QuitAfterGameStop.cpp
> +}
ok

2022-03-27 18:56 UTC, merged