Add option to install mod loader during instance creation
PolyMC/PolyMC pull request #398
Opened 2022-04-04 23:48 UTC by kthchew

This adds an option to install Forge, Fabric, or LiteLoader while creating a new instance. Closes #137.

What I currently have is below:

https://user-images.githubusercontent.com/79120643/161649230-25a5d72b-a86b-434c-a3e7-c461544edc25.mov

The UI may need a second look.

- Should the mod loader selection UI be visible in the "Vanilla" tab, or should a new tab be made for this?
- If this functionality stays in the "Vanilla" tab, should its name be changed?
- Should the mod loader list be more like the experience while installing a mod loader on a preexisting instance? In that case, [a new dialog opens over the window](https://user-images.githubusercontent.com/79120643/161650317-170000ab-617e-4219-a73d-98f24d63e044.png), showing a list of mod loader versions. In comparison, my solution shows them side-by-side in the same window.
- I tried to get a message to show at the bottom when the new instance window first opens to tell the user that no mod loader is selected, but wasn't able to get it to work. The message only shows when selecting a mod loader and then selecting "None" again. I'm not sure why.

2022-04-05 14:35 UTC, glowiak commented
Nice. Btw, what's the distro you're using?

2022-04-05 15:27 UTC, DioEgizio commented
> Nice. Btw, what's the distro you're using?

You don't see? it's literally MacOS...

2022-04-05 15:27 UTC, DioEgizio commented
This pr is made by the one who made the brew package (Ty btw)

2022-04-05 17:09 UTC, DioEgizio commented
> FAILED: launcher/CMakeFiles/Launcher_logic.dir/ui/pages/modplatform/VanillaPage.cpp.o 
/usr/bin/c++ -DLAUNCHER_JARS_LOCATION=share/jars -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DQUAZIP_STATIC -I/home/runner/work/PolyMC/PolyMC/build/launcher -I/home/runner/work/PolyMC/PolyMC/launcher -I/home/runner/work/PolyMC/PolyMC/build/launcher/Launcher_logic_autogen/include -I/home/runner/work/PolyMC/PolyMC/libraries/systeminfo/include -I/home/runner/work/PolyMC/PolyMC/libraries/classparser/include -I/home/runner/work/PolyMC/PolyMC/libraries/quazip -I/home/runner/work/PolyMC/PolyMC/libraries/quazip/quazip -I/home/runner/work/PolyMC/PolyMC/libraries/libnbtplusplus/include -I/home/runner/work/PolyMC/PolyMC/build/libraries/libnbtplusplus -I/home/runner/work/PolyMC/PolyMC/libraries/optional-bare/include -I/home/runner/work/PolyMC/PolyMC/libraries/tomlc99/include -I/home/runner/work/PolyMC/PolyMC/buildconfig -I/home/runner/work/PolyMC/PolyMC/libraries/katabasis/include -I/home/runner/work/PolyMC/PolyMC/libraries/iconfix -I/home/runner/work/PolyMC/PolyMC/build/libraries/iconfix -I/home/runner/work/PolyMC/PolyMC/libraries/hoedown/include -I/home/runner/work/PolyMC/PolyMC/libraries/LocalPeer/include -I/home/runner/work/PolyMC/PolyMC/libraries/rainbow/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtConcurrent -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -Wall -pedantic -Werror -Wno-deprecated-declarations -D_GLIBCXX_USE_CXX11_ABI=0 -fstack-protector-strong --param=ssp-buffer-size=4 -O3 -D_FORTIFY_SOURCE=2  -DQT_NO_DEPRECATED_WARNINGS=Y -g -Werror=return-type -fPIC -fPIC -std=gnu++11 -MD -MT launcher/CMakeFiles/Launcher_logic.dir/ui/pages/modplatform/VanillaPage.cpp.o -MF launcher/CMakeFiles/Launcher_logic.dir/ui/pages/modplatform/VanillaPage.cpp.o.d -o launcher/CMakeFiles/Launcher_logic.dir/ui/pages/modplatform/VanillaPage.cpp.o -c /home/runner/work/PolyMC/PolyMC/launcher/ui/pages/modplatform/VanillaPage.cpp
/home/runner/work/PolyMC/PolyMC/launcher/ui/pages/modplatform/VanillaPage.cpp: In constructor ‘VanillaPage::VanillaPage(NewInstanceDialog*, QWidget*)’:
/home/runner/work/PolyMC/PolyMC/launcher/ui/pages/modplatform/VanillaPage.cpp:64:48: error: ‘idToggled’ is not a member of ‘QButtonGroup’
   64 |     connect(ui->loaderBtnGroup, &QButtonGroup::idToggled, this, &VanillaPage::loaderFilterChanged);
      |                                                ^~~~~~~~~
[364/492] Building CXX object launcher/CMakeFiles/Launcher_logic.dir/ui/pages/global/APIPage.cpp.o
[365/492] Building CXX object launcher/CMakeFiles/Launcher_logic.dir/ui/pages/modplatform/ModPage.cpp.o
ninja: build stopped: subcommand failed.
Error: Process completed with exit code 1.

from the CI

2022-04-05 17:13 UTC, kthchew commented
Oh, I think I might’ve used a different version of Qt on my local machine, oops. I’ll look into it soon.

2022-04-05 17:49 UTC, kthchew commented
@DioEgizio I had to compare to the Qt documentation because I didn't have time to setup my local environment with Qt 5.6, but I think the latest commit should fix the build.

2022-04-05 17:52 UTC, DioEgizio commented
Oh, i hope it does then

2022-04-06 14:16 UTC, ZekeSmith commented
Ill approve the gha run and we can see if it works with our tooling. This looks like a great feature addition from what I can see.

2022-04-06 14:17 UTC, DioEgizio commented
<img width="795" alt="immagine" src="https://user-images.githubusercontent.com/83089242/161995944-9c58ab93-7ec1-466d-9c5b-cd97068ff5ea.png">
what
ignore that i guess

2022-04-06 15:32 UTC, DioEgizio requested changes
i was testing this, and i found a bug. If you select a modloader and then a version (which the modloader doesn't support) it will create the instance anyways

2022-04-06 15:33 UTC, DioEgizio commented
<img width="1178" alt="Schermata 2022-04-06 alle 17 32 53" src="https://user-images.githubusercontent.com/83089242/162012236-1c7ac241-7f3f-480d-8e28-933042f1900f.png">
like, for example

2022-04-06 15:33 UTC, DioEgizio commented
<img width="1201" alt="Schermata 2022-04-06 alle 17 33 20" src="https://user-images.githubusercontent.com/83089242/162012341-855a21f6-9863-4425-9213-f020c0dd928f.png">
and then this happens

2022-04-06 15:34 UTC, DioEgizio commented
seems to be an issue only for fabric

2022-04-06 15:35 UTC, DioEgizio commented
also i think the "Vanilla" tab should be "Custom" here

2022-04-06 16:06 UTC, Scrumplex commented
The launcher doesn't do much dependency resolution here and is basically unaware if Fabric is supported on a version or not. There is some ugly hack somewhere that just hides the "Install Fabric" button on older versions

2022-04-06 16:14 UTC, kthchew commented
> The launcher doesn't do much dependency resolution here and is basically unaware if Fabric is supported on a version or not. There is some ugly hack somewhere that just hides the "Install Fabric" button on older versions

Found it: https://github.com/PolyMC/PolyMC/blob/335115041caeab19b80c2ffd53036bfd6af10013/launcher/ui/pages/instance/VersionPage.cpp#L243

Don’t have time right now, but I’ll try to push a similar solution for now to fix that issue once I do.

2022-04-06 16:15 UTC, DioEgizio commented
> The launcher doesn't do much dependency resolution here and is basically unaware if Fabric is supported on a version or not. There is some ugly hack somewhere that just hides the "Install Fabric" button on older versions

HACK HACK HACK HACK FIXME?

2022-04-06 18:09 UTC, Scrumplex commented
> Don’t have time right now, but I’ll try to push a similar solution for now to fix that issue once I do.

yeah totally fine way to do it for now

2022-04-06 20:59 UTC, kthchew commented
Fabric issue fixed

2022-04-07 13:23 UTC, DioEgizio commented
yes now fabric works fine

2022-04-14 09:09 UTC, DioEgizio commented
> Should the mod loader selection UI be visible in the "Vanilla" tab, or should a new tab be made for this?
If this functionality stays in the "Vanilla" tab, should the tab's name be changed?
Should the mod loader list be more like the experience while installing a mod loader on a preexisting instance? In that case, [a new dialog opens over the window](https://user-images.githubusercontent.com/79120643/161650317-170000ab-617e-4219-a73d-98f24d63e044.png), showing a list of mod loader versions. In comparison, my solution shows them side-by-side in the same window.

I personally think UI/UX is ok as it is now but the "Vanilla" instance name'd be changed to something different like "Custom"

2022-04-14 16:50 UTC, kthchew commented
> I personally think UI/UX is ok as it is now but the "Vanilla" instance name'd be changed to something different like "Custom"

Makes sense. I'll see about changing that in a bit.

2022-04-14 17:25 UTC, Scrumplex approved these changes
LGTM, Thanks!

2022-04-14 17:27 UTC, Scrumplex commented
> I personally think UI/UX is ok as it is now but the "Vanilla" instance name'd be changed to something different like "Custom"

Nah, Vanilla should be fine. Just installing a mod loader doesn't alter gameplay, so most people would still consider it Vanilla.

2022-04-14 23:38 UTC, ZekeSmith approved these changes

2022-04-15 03:39 UTC, txtsd approved these changes

2022-04-15 09:43 UTC, DioEgizio commented
this needs to be updated to support Quilt

2022-04-15 10:49 UTC, Scrumplex requested changes
needs Quilt as @DioEgizio already mentioned
See #185

2022-04-15 19:06 UTC, kthchew commented
I think Quilt should work now. I'm not very knowledgeable about Quilt, but I'm assuming it has the same MC version requirements as Fabric? If so, then the current code should work fine.

2022-04-15 19:34 UTC, Scrumplex commented
Looks like your branch doesn't include my merged Quilt PR. Can you rebase?

```
git remote add upstream https://github.com/PolyMC/PolyMC.git  # if you don't already have this repo as a remote
git fetch upstream

git rebase upstream/develop

# rebase needs a force push
git push --force
```

2022-04-15 19:37 UTC, kthchew commented
Done

2022-04-15 20:14 UTC, Scrumplex approved these changes

2022-04-15 20:15 UTC, Scrumplex commented
Thanks! Gonna merge this once the builds finish

2022-04-15 20:36 UTC, merged