Flatpak Packaging
PolyMC/PolyMC pull request #4
Opened 2021-12-27 08:33 UTC by dada513

Closes #3 
Bundles java 8,11,16,17. PR contains additional patch for PolyMC to automatically detect flatpak java versions.
Contains desktop integration, without icon yet as #1 hasnt yet been closed

When this is merged I will try to get it on flathub

2021-12-27 16:29 UTC, LennyMcLennington requested changes
There needs to be a way to specify the package version when building the deb package. I don't know how the version works on flatpak, as long as you can specify the version when building the flatpak then that will be ok.

2021-12-27 16:29 UTC, LennyMcLennington commented on packages/debian/polymc/DEBIAN/control
> +Version: 1.0.0
I don't think this should just be 1.0.0, it should be the actual PolyMC version.

2021-12-27 16:29 UTC, LennyMcLennington commented on packages/debian/polymc/usr/share/applications/polymc.desktop
> +Version=1.0.0
`Version` key does not stand for the version of the application, but for the version of the desktop entry specification to which this file complies. It shouldn't have been changed from 1.0 to 1.0.0

2021-12-27 16:29 UTC, LennyMcLennington commented on packages/flatpak/org.polymc.PolyMC.desktop
> +Version=1.0.0
Same issue as the debian .desktop file

2021-12-27 18:15 UTC, dada513 commented
Fixed deb. Uses latest git tag as version.
For flatpak, I will set a git tag too, but I need a new tag to be released which contains the patches from PolyMC (current latest tag is using peterix build stuff)

2021-12-28 14:09 UTC, binex-dsk commented
@dada513 if you could commit in accordance with my reviews that would be appreciated.

2021-12-28 15:05 UTC, dada513 commented
> @dada513 if you could commit in accordance with my reviews that would be appreciated.

I dont know if GitHub is bugged but I don't see your review

2021-12-28 15:07 UTC, binex-dsk reviewed
I forgot to submit it

2021-12-28 15:07 UTC, ghost commented on packages/debian/makedeb.sh
> +sed -i "2s/.*/Version: Set to latest git tag by makedeb.sh at build time/" polymc/DEBIAN/control
This is kinda weird and long. It can just be VERSION_PLACEHOLDER (so `sed -i '2s/.*/Version: VERSION_PLACEHOLDER`)

2021-12-28 15:07 UTC, ghost commented on packages/debian/polymc/DEBIAN/control
> +Version: Set to latest git tag by makedeb.sh at build time
""

2021-12-28 15:07 UTC, ghost commented on packages/debian/makedeb.sh
> +sed -i "2s/.*/Version: Set to latest git tag by makedeb.sh at build time/" polymc/DEBIAN/control
It'd also be beneficial to create a separate template control file. This way, you could simply sed with an input (template control) and output (actual control), and then there's no need to use the second sed command

2021-12-28 15:41 UTC, dada513 commented
@binex-dsk done

2021-12-28 15:44 UTC, binex-dsk commented
Thanks! Looks good.

2021-12-28 15:45 UTC, merged