Cleanup mess, make theme and icon theme change instantly
PolyMC/PolyMC pull request #512
Opened 2022-04-30 18:04 UTC by dada513

2022-04-30 18:07 UTC, dada513 commented
tf is there a conflict

2022-05-03 14:51 UTC, txtsd commented
segfaulted once for me when switching from dark to system, but I haven't been able to reproduce it.

<details>

```
λ coredumpctl gdb 72127                                                                                                                                                                      
           PID: 72127 (polymc)
           UID: 1000 (txtsd)
           GID: 985 (users)
        Signal: 11 (SEGV)
     Timestamp: Tue 2022-05-03 20:16:40 IST (2min 52s ago)
  Command Line: /home/txtsd/git/polymc/PolyMC/install/polymc -d /home/txtsd/git/polymc/PolyMC/install
    Executable: /home/txtsd/git/polymc/PolyMC/install/bin/polymc
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-kitty.slice/app-kitty-5646.scope
          Unit: user@1000.service
     User Unit: app-kitty-5646.scope
         Slice: user-1000.slice
     Owner UID: 1000 (txtsd)
       Boot ID: d02589c2bd644cbc8aa1346d91098404
    Machine ID: 6b72ccca048b44a48267cc003f28b3bf
      Hostname: dungeon-of-data
       Storage: /var/lib/systemd/coredump/core.polymc.1000.d02589c2bd644cbc8aa1346d91098404.72127.1651589200000000.zst (present)
     Disk Size: 4.5M
       Message: Process 72127 (polymc) of user 1000 dumped core.
                
                Module /home/txtsd/git/polymc/PolyMC/install/bin/polymc with build-id fe80a038dc35fa664045105b1a1fd0388540d869
                Module linux-vdso.so.1 with build-id b7607809b317f818513518299d3a137bb63a1392
                Module libdatrie.so.1 with build-id 6fe3b6ece2c8e7d11869fa051375128d8f808f58
                Module libthai.so.0 with build-id a7ac5010b4275c49308021200d23690533952702
                Module libwebp.so.7 with build-id 0add7a572705244ed810b7e722cce7da0dcfb62c
                Module libwebpdemux.so.2 with build-id 7bc15ac239db643015e169a2c6cc822156eb999a
                Module libwebpmux.so.3 with build-id 4232d5263a45719ba12f58ed7d8cae3a0fc887de
                Module libqwebp.so with build-id dacb86849cf63601c096302bc5248957f26c1792
                Module libqwbmp.so with build-id f364a39e41da7b352070f5b0d1a0330479eb0f3d
                Module libtiff.so.5 with build-id 9e8868622f8b7144fd82dabfa8ac2fcaf6d45a34
                Module libqtiff.so with build-id b37ad8ac140e0c9543378e4c326613a1311b2295
                Module libqtga.so with build-id 6a0d436c0b5fba0310da77a06cf93ffb0cd9d32a
                Module libqsvg.so with build-id 5a05e2dce49105d54df27dedbaf767fed536cf54
                Module libQt5Pdf.so.5 with build-id 7dac10389a608991a7ccd577bdf920e2845a24e6
                Module libqpdf.so with build-id dc89e07f30c673dc4e16045e8ed4446f0b79a28b
                Module liblcms2.so.2 with build-id c01e5649a38dbf37768d02dc751b52de0dcbd141
                Module libmng.so.2 with build-id 2de13b8bba73f358ab2e323aa2209c2e2fc886e7
                Module libqmng.so with build-id 9d7d2aea82b20085d0fe175021ffaba5f838f4f7
                Module libqjpeg.so with build-id 8f3fd514e6a0e33f6c43a88045271ca1e38fe721
                Module libjpeg.so.8 with build-id 324d9d66f01707241e31af5cc104db3c9122f4c4
                Module libjasper.so.4 with build-id e787106c7e64916a594d31088a7a099d19a5fdfb
                Module libqjp2.so with build-id dc19aeb06d63cb2c80fb2a3cbeea2e117e073cdc
                Module libqico.so with build-id c10d08a71544a009ff12fd922652abb0e14bbc31
                Module libqicns.so with build-id 685f743bf4bce33832bb725d0fc7c93548c9e302
                Module libqgif.so with build-id 39b4fe207c1219ed12d22aa7c37396fbe0466e75
                Module libQt5Svg.so.5 with build-id f7022a2f8451f8b6317ed423207a2f17c647ec90
                Module libqsvgicon.so with build-id 94e7ac483e3cc24b5709cbcf02825dd01ce4aff8
                Module libnss_resolve.so.2 with build-id a6a782fb6661cb7bf4d167313115e3fe1a517752
                Module libnss_mdns.so.2 with build-id ebe657483802a9a76a10b1e2381b64d49cc32c34
                Module libnss_myhostname.so.2 with build-id f02371b14b0605c1501ab8ac48384376970c6143
                Module libnss_mymachines.so.2 with build-id 0603426c0dd45a339e94969ad56ec94ea0b6871f
                Module gost.so with build-id 4c47df63c920e79898641f92307a66cb82991dce
                Module libxdg-shell.so with build-id 9a7eb13e2c3223f4947f06de92a22b278f574716
                Module libxml2.so.2 with build-id 6b0ec2acdbc8f1a2255cc5e3e1258472cd99e272
                Module libncursesw.so.6 with build-id 1f873ddb2c32ab39d0b7d8646d03680ffe99de7c
                Module libedit.so.0 with build-id 4b0babfcad161c2ad0af6e59e2493258db23a331
                Module libvulkan.so.1 with build-id 9a68026d3ebb939eab0b6165c10596468560db5e
                Module libdrm_nouveau.so.2 with build-id af8afb2331ac08c52132102ecbdc6076a8eb4c6f
                Module libdrm_amdgpu.so.1 with build-id 8eb3977b830f3012d9ead7b4def5f4d2f38ec688
                Module libelf.so.1 with build-id 4cf96cb4785e1ca233693ae17fa0d62971ee09c2
                Module libdrm_radeon.so.1 with build-id 43e0aecc70c4ce905ba35c948e1c9a5d999b14c0
                Module libsensors.so.5 with build-id dc8b2c1c0d8525411aca188ea3cc3fb86d381d30
                Module libLLVM-13.so with build-id 76d1fe97dbdca6d6891c6a1a7c06a388aa247154
                Module radeonsi_dri.so with build-id 2c924a3c23ae18ded3255d5b83fea9a8bf3d2af8
                Module libxshmfence.so.1 with build-id 8876d9ccf620858795724ca24b9e567585a77cec
                Module libxcb-sync.so.1 with build-id dda14591103b01b1311906053bf1ca9e82ade35c
                Module libxcb-present.so.0 with build-id 68f5465258750e2397b1333b3ffc01ee33caa4e1
                Module libxcb-dri3.so.0 with build-id 9407a2480e09dc5a1dd9d9a0652fa8d32b328c91
                Module libwayland-server.so.0 with build-id 5526cec43774a83c7ab8c7ff820eea8b28880d51
                Module libdrm.so.2 with build-id 00816f0a71c7e4e388c10db6245dbb9c031732a9
                Module libxcb-xfixes.so.0 with build-id a6b197ace5b9b59f913f5969eb419a88d1194f47
                Module libxcb-dri2.so.0 with build-id 2dd6e65129a809dab828a1d26215a3f7a363fcc8
                Module libX11-xcb.so.1 with build-id f6beacd41cd16a23f53e5e56bb599e98f039d0d6
                Module libglapi.so.0 with build-id b8a35e2049e102a7e69039443c0b3aacbbf4eaa6
                Module libgbm.so.1 with build-id 33713af0b01128039d0ab0f952ca068f8b43f8f0
                Module libEGL_mesa.so.0 with build-id aed3c03444f48aed40bc9c94fc7f83170a51c9f7
                Module libwayland-egl.so.1 with build-id ac45e227422559ff92c4d04851fffb8452874713
                Module libEGL.so.1 with build-id 686c2e4036c01a3a72349ed0dd04f7c434af14ce
                Module libqt-plugin-wayland-egl.so with build-id 80f7f382249c5f73327e31fe7bea28bf163cd809
                Module libqnmbearer.so with build-id 875ae099ce2d2b71d1635b76e03d9bed9c60b9b9
                Module libqgenericbearer.so with build-id c85ce4e63cd742702965926c2c269503bd0f3a4f
                Module libqconnmanbearer.so with build-id caa91d79eed786a9c42743513cdf1539876a425f
                Module libqt5ct-style.so with build-id 3cc7fc2771ccbb881129f7336295c37cb1484213
                Module libqt5ct.so with build-id 9417235459a81cdac223a735568ecc7aef5a4d3f
                Module libcomposeplatforminputcontextplugin.so with build-id 21084422e8f6910b5e50e5b059e60e221b20c049
                Module libdbus-1.so.3 with build-id 7f4b16b4b407cbae2d7118d6f99610e29a18a56a
                Module libexpat.so.1 with build-id 113bb5a3e9ad856801bfcfc029102c9bdc13d67e
                Module libffi.so.8 with build-id f0a9586cf0f42d2b9971bd1065ca3a6b19f4a2c2
                Module libxkbcommon.so.0 with build-id 3a9338b2085f0af41217bc0a90ffcc941938a16e
                Module libQt5DBus.so.5 with build-id eaadac7eb0682c8accdb8431fb928470c0546840
                Module libfontconfig.so.1 with build-id 36be6951b8c1e42a7dd05684a37400fc8ef9147c
                Module libwayland-client.so.0 with build-id [...]

2022-05-03 14:52 UTC, txtsd approved these changes

2022-05-03 15:11 UTC, dada513 commented
> segfaulted once for me when switching from dark to system, but I haven't been able to reproduce it.

cant reproduce, doesnt matter + wontfix :trol:

2022-05-03 18:48 UTC, kthchew requested changes
When opening PolyMC settings, my theme is immediately set to bright, and the following warnings appear in the log:

```
   82.235 W QMetaObject::connectSlotsByName: Connecting slot on_themeComboBox_currentIndexChanged() with the first of the following compatible signals: ("currentIndexChanged(int)", "currentIndexChanged(QString)")
   82.235 W QMetaObject::connectSlotsByName: Connecting slot on_themeComboBoxColors_currentIndexChanged() with the first of the following compatible signals: ("currentIndexChanged(int)", "currentIndexChanged(QString)")
   82.236 W Tried to set invalid theme: ""
```

https://user-images.githubusercontent.com/79120643/166521871-b94d1789-fb36-42e6-9119-04b3b500c662.mov

(ignore the weird dark/light mix bug, that's something unrelated to this PR)

2022-05-03 19:18 UTC, d-513 commented
wow thats a big issue. How tf is this happening though? I cant reproduce, do you have any idea how this can be fixed?

2022-05-03 19:24 UTC, kthchew commented
There seems to be a combination of issues here (at least on my system) that I gleaned from debugging:

1. For some reason, `s->get("ApplicationTheme").toString()` is returning "" on my system. However, my `polymc.cfg` clearly has a `ApplicationTheme=system` line. I'm not sure why this happens; it doesn't seem like your PR should affect this at all.
2. While looping over the `appThemes` and adding the themes to `themeComboBoxColors`, it seems that once the first theme is added, `applyThemeSettings` runs. Maybe this could be resolved if there was something to prevent `applyThemeSettings` from running immediately once the settings dialog is opened.

2022-05-03 19:26 UTC, dada513 commented
Hmm, so Qt seems to be triggering the slots every time a new item is added. It hasn’t caused problems on my side for some reason, but it’s definitely problematic.

2022-05-03 19:27 UTC, kthchew commented
For clarification, `applyThemeSettings` doesn't run after every item is added. It only seems to run after the first item is added.

2022-05-03 20:01 UTC, kthchew commented
The same also applies to icons. They're always set to "Simple (Colored Icons)" when opening the settings dialog. 

Similar second issue, but as for the first one, `auto iconTheme = s->get("IconTheme").toString();` seems to be setting `iconTheme` to `pe_colored`, even though I set something like (for example) `IconTheme=flat` in my `polymc.cfg`. Again, I have no idea why.

2022-05-03 20:06 UTC, kthchew commented
Also can reproduce a crash (maybe this is the same crash @txtsd mentioned), reproduction steps:

1. Remove your PolyMC data folder (or just rename it so that PolyMC acts as if it was never started before)
2. Go through the setup screens as normal
3. In PolyMC settings, change either the icon or the colors to anything
4. Change either the icon or the colors to anything else again; a crash will occur

2022-05-04 20:33 UTC, kthchew commented
> 1. Remove your PolyMC data folder (or just rename it so that PolyMC acts as if it was never started before)
> 2. Go through the setup screens as normal
> 3. In PolyMC settings, change either the icon or the colors to anything
> 4. Change either the icon or the colors to anything else again; a crash will occur

Coming back to add that the crash is not the fault of this PR. It is also reproducible in the latest develop build. You just have to close the settings dialog after steps 3 and 4 (to get the theme to actually change), and the same crash occurs.

Still probably worth fixing if possible though, since it's easier to reproduce with this PR.

2022-06-15 09:38 UTC, flowln commented
_poking old PR to see if it gets picked up again_ ^-^

2022-06-15 15:35 UTC, dada513 commented
> _poking old PR to see if it gets picked up again_ ^-^

Truly a dada513 moment. I’m on vacation :trol:

2022-06-15 23:00 UTC, LennyMcLennington requested changes

2022-06-15 23:00 UTC, LennyMcLennington commented on launcher/Application.h
> +
Why not use an array or vector of pairs/tuples/structs instead of two separate string lists?

2022-06-15 23:00 UTC, LennyMcLennington commented on launcher/ui/pages/global/LauncherPage.h
> +    void on_themeComboBoxColors_currentIndexChanged();
Shouldn't we explicitly use connect() instead of using auto-connection in new code? This is quite error-prone, as simply renaming the object that the connection is being made for is going to silently cause the connection to not be made. That's in addition to the fact that you have to define two one-line functions just to call another function whereas by using connect() you can just directly connect the signals to the applyThemeSettings function.

2022-06-15 23:00 UTC, LennyMcLennington commented on launcher/ui/pages/global/LauncherPage.cpp
> +    for(auto &displayIconTheme: displayIconThemes)
nitpick
```suggestion
    for (auto &displayIconTheme : displayIconThemes)
```

2022-07-06 13:14 UTC, DioEgizio commented
any updates on this pr?

2022-07-07 09:09 UTC, dada513 commented
> any updates on this pr?

No

2022-08-02 14:29 UTC, DioEgizio commented
dead pr

2022-08-03 20:16 UTC, Scrumplex commented
Reopen, if you want to continue work on this

2022-08-03 20:16 UTC, closed without merging