Default to system locale language
PolyMC/PolyMC pull request #52
Opened 2022-01-12 17:03 UTC by oynqr

With these changes PolyMC will try to default to the system locale on first startup.

This is honestly a bit hacky, since it's my first time working with QT/this codebase, but I don't think it's much worse than the surrounding code.

2022-01-12 18:54 UTC, binex-dsk commented
I believe people wanted it to have the locale selected as well. If you could do that it'd be great.

Add a "Closes" to this so it automatically closes the related issue.

2022-01-12 19:11 UTC, binex-dsk requested changes

2022-01-12 19:11 UTC, binex-dsk commented on launcher/translations/TranslationsModel.cpp
> +    if (langCode.length() == 0)
just use `langCode.empty()`

2022-01-13 09:23 UTC, oynqr commented on launcher/translations/TranslationsModel.cpp
> +    if (langCode.length() == 0)
Done.

2022-01-13 09:38 UTC, oynqr commented
This should address most, if not all, of the issue. If there is a corresponding language to the system locale, it should always be at the top of the list and it will also be highlighted/selected.
Please note that this changes the behavior in case the user terminates PolyMC with the initial language selector still open, as it will no longer open it on subsequent starts since the language config was set to the locale default or American English if there is no translation available.

I have not and can not test this on Mac OS/Windows, so that would be appreciated.

2022-01-13 13:18 UTC, binex-dsk commented
Can't test on MacOS but can on Windows sometime later.

2022-01-15 21:58 UTC, oynqr commented
I might spin up a macOS VM to test this tomorrow.

2022-01-17 10:14 UTC, oynqr commented
Seems like it's hitting this on macOS: https://bugreports.qt.io/browse/QTBUG-72491. Creating the relevant .lproj directories manually fixes it.

2022-01-19 17:56 UTC, binex-dsk commented
I have literally no clue how to compile on windows, and I really don't feel like using MinGW. I'm going to assume it works on windows.

Later I will test this out.

2022-01-23 20:00 UTC, binex-dsk commented
works on Windows

2022-01-23 20:00 UTC, merged