Fix toolbar disappearing in a certain circumstance
PolyMC/PolyMC pull request #577
Opened 2022-05-16 23:26 UTC by LennyMcLennington

Closes #573
Kind of, because it prevents the bug from occurring again, but it doesn't fix existing bugged configs. The bug hasn't been reported before, but it might be good to add some mechanism to fix bugged configs in case someone comes across it before updating to the version of PolyMC that would have the fix in it. Idk, tell me what you think if that is a good idea or overkill.

2022-05-16 23:31 UTC, kthchew commented
> ninja: error: rebuilding 'build.ninja': GetFileAttributesEx(../.git/refs/heads/fix/toolbar_??_fix): The filename, directory name, or volume label syntax is incorrect.

Looks like Windows hates Unicode (`fix/toolbar_🦀_fix`). It'll probably be fine when merged.

> but it doesn't fix existing bugged configs

When the bug occurs, does pressing 'alt' still show the menu bar? If so, it should be recoverable since a user should be able to access settings from there.

2022-05-16 23:43 UTC, LennyMcLennington commented
> > ninja: error: rebuilding 'build.ninja': GetFileAttributesEx(../.git/refs/heads/fix/toolbar_??_fix): The filename, directory name, or volume label syntax is incorrect.
> 
> Looks like Windows hates Unicode (`fix/toolbar_🦀_fix`). It'll probably be fine when merged.
> 
> > but it doesn't fix existing bugged configs
> 
> When the bug occurs, does pressing 'alt' still show the menu bar? If so, it should be recoverable since a user should be able to access settings from there.

Yeah I think it still shows the menu bar so it should be fine. Funny that windows can't handle a crab emoji lol.

2022-05-16 23:44 UTC, kthchew commented
> Yeah I think it still shows the menu bar so it should be fine.

Ah okay. It's probably fine to just help the few people who encounter the issue fix it then.



> Funny that windows can't handle a crab emoji lol.

Windows is 🦀

2022-05-17 00:07 UTC, LennyMcLennington commented
Kinda weird that it some windows builds worked but some failed from the emoji, is it instead a problem with the way the actions are set up?

2022-05-17 00:10 UTC, kthchew commented
> Kinda weird that it some windows builds worked but some failed from the emoji, is it instead a problem with the way the actions are set up?

The PR actions succeeded, but the push actions failed. I'm guessing that PR actions are treated differently by GHA, and the path no longer contains the original branch name for PR actions (but that's a guess, and I'm not entirely familiar with it).

2022-05-18 06:14 UTC, Scrumplex commented
Maybe just rename the branch to avoid breakage

2022-05-20 02:34 UTC, LennyMcLennington commented
> Maybe just rename the branch to avoid breakage

Can't rename it after the PR is made, and it won't break on the main branch which is what it would be merged into.

2022-05-20 20:05 UTC, Scrumplex requested changes
This looks hacky to me. Maybe just call `updateMainToolBar()` after creating the menubar and toolbar: https://github.com/PolyMC/PolyMC/blob/6dfec4db40f09697f34f65419edb7d689e3c5dc7/launcher/ui/MainWindow.cpp#L809-L813

2022-05-20 20:14 UTC, LennyMcLennington commented
> This looks hacky to me. Maybe just call `updateMainToolBar()` after creating the menubar and toolbar:
> 
> https://github.com/PolyMC/PolyMC/blob/6dfec4db40f09697f34f65419edb7d689e3c5dc7/launcher/ui/MainWindow.cpp#L809-L813

Have you tested to see if it will work? The state is restored after setupUi is called, so I don't see how it would work.

2022-05-20 20:27 UTC, Scrumplex commented
Okay seems like that actually doesn't work.

Maybe we should just split up the option into two:

One checkbox for showing the toolbar, and one for showing the menu bar.

2022-05-21 09:44 UTC, Scrumplex approved these changes

2022-05-21 09:44 UTC, Scrumplex commented
Fine for now I guess

2022-05-22 15:36 UTC, txtsd approved these changes

2022-05-22 15:47 UTC, flowln approved these changes

2022-05-22 16:11 UTC, merged