Native and jar override
PolyMC/PolyMC pull request #666
Opened 2022-05-28 23:48 UTC by r58Playz

Added a native override and jar override as a stopgap for implementing ARM support in the meta.

This allows you to specify precompiled natives and patched jars for instances.

<img width="805" alt="Native and jar override config" src="https://user-images.githubusercontent.com/45221816/170846218-d8072f48-ed50-4b03-ba4e-c8576aeb4b33.png">

2022-05-29 07:16 UTC, ryanccn requested changes

2022-05-29 07:16 UTC, ryanccn commented on launcher/ui/pages/instance/InstanceSettingsPage.ui
> +          <string>Jar file location</string>
Maybe call it "Libraries"

2022-05-29 07:17 UTC, ryanccn commented
Also, is this just LWJGL or all the libraries?

2022-05-29 07:17 UTC, r58Playz commented
> Also, is this just LWJGL or all the libraries?

All the libraries

2022-05-29 09:52 UTC, Scrumplex commented
I don't know if I like this or not. Makes stuff harder to debug once people start using this, as there is no source of truth anymore. This also kinda duplicates a feature, as you can always switch out libraries by editing the components for an instance (Edit Instance -> Select component -> Customize -> Edit). That's how I tested various different things related to libraries.

2022-05-29 10:31 UTC, glowiak commented
Finally. I hope this will got merged to 1.3.1

2022-05-29 14:31 UTC, ryanccn commented
IMO it would be better if the overrides was a table mapping Maven IDs to JARs. Downloading all the libraries by the user themselves seems to be too much bloat, and would result in a lot of duplication.

2022-06-20 14:54 UTC, flowln commented
So, what's the state of this? Do we want it or not? x.x

2022-06-20 15:00 UTC, r58Playz commented
Closing this PR, since actual multi-arch support is very close to done.

2022-06-20 15:00 UTC, closed without merging