Make the fluffy kitty button meow :3
PolyMC/PolyMC pull request #774
Opened 2022-06-10 06:26 UTC by TheEssem

2022-06-10 06:32 UTC, DioEgizio commented
To not make ci fail, add qtmultimedia5-dev to https://github.com/PolyMC/PolyMC/blob/309013efb3e148310ba4802ee946a55c01d1d56e/.github/workflows/build.yml#L124

2022-06-10 07:06 UTC, DioEgizio commented
doesn't work for me, doesn't meow D:

2022-06-10 07:13 UTC, timoreo22 commented
to fix the ubuntu appimage build, adding `libqt5multimedia5-plugins` as another package to install would probably fix it
still on the same line
https://github.com/PolyMC/PolyMC/blob/309013efb3e148310ba4802ee946a55c01d1d56e/.github/workflows/build.yml#L124

2022-06-10 07:16 UTC, ryanccn commented
jump scare

2022-06-10 09:46 UTC, jn64 commented
The original sound is a bit loud and has some harshness. I've normalised it so it is in line with the loudness of freedesktop bell alert sound (probably the most common alert sound on Linux desktops, just picked as an example as I do not have access to other OS) and filtered some of the high frequencies.

[meow-normalised-filtered3.zip](https://github.com/PolyMC/PolyMC/files/8877622/meow-normalised-filtered3.zip) - please use this if it is acceptable

I did not match the change you made to the length of the file as I don't know if that was intentional (the sound in the PR has a negligible ~11ms of silence added to the front of the original)

2022-06-10 11:21 UTC, forkiesassds commented
Why? Why do we need to add a dependency just for one joke feature?

2022-06-10 12:32 UTC, Regular-Baf commented
> Why? Why do we need to add a dependency just for one joke feature?

Because it's awesome. God bless you @TheEssem

2022-06-10 12:33 UTC, Regular-Baf approved these changes
No clue what any of this does but it has my vote.

2022-06-10 12:47 UTC, zzcolby27 approved these changes
Based and catpilled

2022-06-10 13:19 UTC, ryanccn approved these changes
It's a joke!

2022-06-10 13:19 UTC, DioEgizio requested changes
Doesn't work D:

2022-06-10 14:24 UTC, OldWorldOrdr commented
merge wen

2022-06-10 14:43 UTC, TheEssem commented
@timoreo22 @jn64 Thanks for the tips, fixed.

2022-06-10 16:45 UTC, Scrumplex commented
hmm. not sure if we want to pull Qt Multimedia just for a meow

2022-06-10 16:49 UTC, TheEssem commented
> hmm. not sure if we want to pull Qt Multimedia just for a meow

Was kinda concerned about that as well, how do you suggest it be done instead? The original issue mentioned it and so that's what I went for

2022-06-10 21:31 UTC, LoganDark commented
Meow :)

2022-06-11 01:33 UTC, forkiesassds commented
> hmm. not sure if we want to pull Qt Multimedia just for a meow

Exactly. Why do we need a multimedia library just for a single feature?

2022-06-12 22:19 UTC, asolidtime commented
If we add a config option to meow (and show a notification) when a modpack or game version finishes downloading, would that better justify pulling qtmultimedia?  /hj
  
  
  
  
  
i didn't realize qsound needed an extra dependency sorry

2022-06-12 22:22 UTC, asolidtime commented
oh, also, wouldn't it be a bit better if it only meowed when the cat was shown, not when it's hidden?

2022-06-15 04:14 UTC, kthchew requested changes

2022-06-15 04:14 UTC, kthchew commented on CMakeLists.txt
> +    find_package(Qt5 REQUIRED COMPONENTS Core Widgets Concurrent Multimedia Network Test Xml)
The [uninstaller section](https://github.com/PolyMC/PolyMC/blob/707a68cb4f71c8de5476064215f49ead011a9038/program_info/win_install.nsi.in#L170-L238) in the script to generate the Windows (un)installer should be updated to remove any file(s) associated with the new multimedia dependency (`Qt5Multimedia.dll`, I think).

```nsis
Delete $INSTDIR\Qt5Multimedia.dll
```

2022-06-15 04:28 UTC, txtsd commented
> hmm. not sure if we want to pull Qt Multimedia just for a meow

How about we leave it in as an easter egg? So if anyone already has Qt Multimedia, it will play the sound. Otherwise the behavior is unchanged.
@Scrumplex

2022-06-21 15:17 UTC, ZekeZDev commented
I like that idea

2022-06-27 14:56 UTC, jamieslyman requested changes
While it would be funny to keep it, I think that `ctaMeow` should be renamed into `catMeow` unless there's a reason not to.

2022-07-02 15:53 UTC, ZekeSmith commented
I think we can all agree while nice this isnt useful and just adds unessecary dependencies. I am going to close this issue but remind me again for 1st of april next year might use it in a custom build.

2022-07-02 15:53 UTC, closed without merging