chore(flame): reword warning
PolyMC/PolyMC pull request #834
Opened 2022-06-23 14:52 UTC by DioEgizio

2022-06-23 15:00 UTC, copygirl requested changes
"Allow to disallow"?
May I suggest "CurseForge provides a setting to creators that disables third-party downloads by tools like PolyMC."?

2022-06-23 15:56 UTC, Scrumplex commented on launcher/ui/pages/modplatform/flame/FlamePage.ui
> +      <string>Note: CurseForge now provides a setting for creators that allows to block access to third-party tools like PolyMC. As such, you may need to manually download some mods to be able to ins
```suggestion
      <string>Note: CurseForge allows creators to block access to third-party tools like PolyMC. As such, you may need to manually download some mods to be able to install a modpack.</string>
```

2022-06-23 15:57 UTC, Scrumplex commented on launcher/ui/pages/modplatform/flame/FlamePage.ui
> +      <string>Note: CurseForge now provides a setting for creators that allows to block access to third-party tools like PolyMC. As such, you may need to manually download some mods to be able to ins
This is my suggestion. A little more concise :D

2022-06-23 22:33 UTC, flowln approved these changes

2022-06-24 08:06 UTC, Scrumplex approved these changes

2022-06-26 15:12 UTC, ZekeSmith approved these changes

2022-06-26 15:12 UTC, merged