Handle network errors for accounts gracefully
PolyMC/PolyMC pull request #877
Opened 2022-07-06 19:42 UTC by Scrumplex

This PR removes offline accounts, and it fixes #85 and possibly other related errors.

2022-07-06 23:18 UTC, flowln commented on launcher/net/NetUtils.h
> +#include <qnetworkreply.h>
```suggestion
```

2022-07-06 23:18 UTC, flowln commented on launcher/net/NetUtils.h
> +        QList<QNetworkReply::NetworkError> errors = {
```suggestion
        static QSet<QNetworkReply::NetworkError> errors = {
```

i think that's a more suitable data structure for this :)

2022-07-07 10:47 UTC, flowln approved these changes
:+1:

2022-07-08 14:48 UTC, txtsd approved these changes

2022-07-19 03:01 UTC, ZekeSmith approved these changes

2022-07-19 05:06 UTC, LennyMcLennington requested changes

2022-07-19 05:06 UTC, LennyMcLennington commented on launcher/net/NetUtils.h
> +            QNetworkReply::InternalServerError,
What's the difference between STATE_FAILED_SOFT and STATE_OFFLINE, and why wouldn't it emit STATE_OFFLINE when there's an internal server error?

2022-07-19 05:22 UTC, LennyMcLennington requested changes
This removes offline accounts but I don't see how it fixes all the cases where accounts are marked as 'expired' despite not being expired. Sure, it does fix other issues and that's good but I don't think it's okay to remove offline accounts until that's fixed.

Please don't remove offline accounts until it's no longer possible for accounts to be marked as expired when they're perfectly valid.

2022-07-19 05:23 UTC, LennyMcLennington commented on launcher/net/NetUtils.h
> +            QNetworkReply::InternalServerError,
nvm

2022-07-19 09:25 UTC, Scrumplex commented
@LennyMcLennington The only cases where an account will be set as "Expired" is when Mojang or MS APIs don't return the necessary information for an account, or return an error. If you have experienced that in the past, then some log output would be helpful. Right now I don't see many potential places where that could happen accidentally (see `launcher/minecraft/auth/Yggdrasil.cpp` and `launcher/minecraft/auth/steps/MSAStep.cpp`, look for `AccountTaskState::STATE_FAILED_HARD`).

In any case, "Play Offline" always worked like this. Offline accounts just don't check this kind of stuff at all.

2022-07-23 10:38 UTC, Scrumplex commented
Moving the removal of offline accounts to a different milestone

2022-07-23 11:24 UTC, LennyMcLennington approved these changes

2022-07-23 11:34 UTC, DioEgizio commented
4 approvals 👀

2022-07-23 11:54 UTC, merged